### ISSUE TITLE
Spell Check: Phase 2

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-tools#1600]
* [ ] Public documentation (so we can open "help wanted" items)
* [ ] Comment in the cspell.json file describing that cspell is not case sensitive and that sorting the words alphabetically is helpful for future users
~* [ ] Describe that minimum version of npm should be present to use npx everywhere we search for npx~ (not using npx now because of [cmd command line length limitation](https://github.com/Azure/azure-sdk-for-cpp/issues/2228#issue-879880488)) 
* [x] Turn on errors per-service (after we have a sufficiently large dictionary of exceptions and errors fixed)
* [x] Add language-specific dictionary to "dictionaries" to prevent false positives in non-source files (e.g. examples in markdown files)
* [ ] Exclude eng/common folder in language repos (eng/common should be checked in tools)

**Comment by pakrym** [comment]
Being able to turn errors on per service directory would be great. I would do it for core and the template immidiately.

**Comment by weshaggard** [comment]
Linking bug https://github.com/Azure/azure-sdk-for-cpp/issues/2228 to this issue as well to ensure we are tracking it to be fixed when we do the next set of spell check changes.

**Comment by danieljurek** [comment]
How do we integrate this into API view?

**Comment by danieljurek** [comment]
The important items from the above list have been completed or are now obsolete based on changes made to how things are done. This can be closed as complete.
