### ISSUE TITLE
ApiView Wishlist

### ISSUE THREAD

**Issue by kurtzeborn** [Azure/azure-sdk-tools#2147]
In a casual lunch meeting today @richardpark-msft suggested it might be interesting to have an open issue to allow folks to add "wishlist" requests.  We can then open separate issues to track them or just resolve this issue when they're all done.

### UI
- [x] Persist user options between reloads of the reviews table. https://github.com/Azure/azure-sdk-tools/issues/2155
- [x] Add option to group reviews by PackageName. https://github.com/Azure/azure-sdk-tools/issues/2114 , https://github.com/Azure/azure-sdk-tools/issues/964
- [x] Show language filter as dropdown. https://github.com/Azure/azure-sdk-tools/issues/2113
- [x] Make syling of components consistent. https://github.com/Azure/azure-sdk-tools/issues/1212
- [x] Add Navigation between comments. https://github.com/Azure/azure-sdk-tools/issues/1205
- [x] Improve responsiveness of review page. https://github.com/Azure/azure-sdk-tools/issues/741
- [x] Prevent the possibilty of multiple clicks of the upload button. https://github.com/Azure/azure-sdk-tools/issues/872
- [ ] You can't have paragraphs in comments. I think this boils down to stripping out newlines in comments.  If we preserve the new lines, it allows commenters to break thoughts into paragraphs which would help with certain types of comments. (just to clarify - multiple newlines get squashed) https://github.com/Azure/azure-sdk-tools/issues/4030
- [ ] It'd be useful if <at> mentions would show me a list of eligible people like a github issue would. https://github.com/Azure/azure-sdk-tools/issues/4031
- [x]  Dark mode / Vision accesibility. https://github.com/Azure/azure-sdk-tools/issues/840

### Backend
- [ ] Show release date for automatic reviews. https://github.com/Azure/azure-sdk-tools/issues/1696

**Comment by mikekistler** [comment]
Closing as all items are now complete or covered by separate issues.
