### ISSUE TITLE
[API view] Include API approval history

### ISSUE THREAD

**Issue by srnagar** [Azure/azure-sdk-tools#2450]
When an API view is approved and then reverted, there's currently no history to show that. It would be good to have a history of changes. Additionally, it would be good to have the ability to add a note when reverting an approval.

```[tasklist]
### Tasks
- [x] Add API approval history showing status, name, date
- [x] Display status comments
- [ ] Add notes/comments section to status UI
```

**Comment by praveenkuttappan** [comment]
Only pending change is to show notes in UI.

**Comment by maririos** [comment]
We’ve decided to prioritize APIView server changes related to Copilot work.
