### ISSUE TITLE
Improve check enforcer responsiveness and operability

### ISSUE THREAD

**Issue by benbp** [Azure/azure-sdk-tools#3033]
Parent issue to capture work to improve check enforcer.

Main goals:

- Improve hourly/daily p50, p95, and p99 check enforcer processing times
- Improve operability of check enforcer
- Improve check enforcer documentation

Issues:

- [ ] https://github.com/Azure/azure-sdk-tools/issues/3030 (small)
- [ ] https://github.com/Azure/azure-sdk-tools/issues/3245 (medium)
- [ ] https://github.com/Azure/azure-sdk-tools/issues/3031 (medium)
- [ ] https://github.com/Azure/azure-sdk-tools/issues/3032 (small and large, two sub-issues)
- [ ] https://github.com/Azure/azure-sdk-tools/issues/3034 (small)
- [ ] https://github.com/Azure/azure-sdk-tools/issues/3035 (large)
- [ ] https://github.com/Azure/azure-sdk-tools/issues/3036 (medium/large, broader than this epic)
- [ ] https://github.com/Azure/azure-sdk-tools/issues/3037 (medium/large)
- [x] https://github.com/Azure/azure-sdk-tools/issues/3041 (medium)
- [ ] https://github.com/Azure/azure-sdk-tools/issues/3040 (medium)
- [ ] https://github.com/Azure/azure-sdk-tools/issues/3155 (large)
- [ ] https://github.com/Azure/azure-sdk-tools/issues/3156 (large)
- [ ] https://github.com/Azure/azure-sdk-tools/issues/3157 (medium)
