### ISSUE TITLE
EngSys Resiliency

### ISSUE THREAD

**Issue by kurtzeborn** [Azure/azure-sdk-tools#3478]
Following the branch deletion post-mortem and other discussions, we've identified a number of improvements we can make to the Azure SDK engineering system to increase resiliency.  Here are issues tracking what we've identified so far:

- [ ] https://github.com/Azure/azure-sdk-tools/issues/3473
   - [ ] https://github.com/Azure/azure-sdk-tools/issues/3472
- [ ] https://github.com/Azure/azure-sdk-tools/issues/3474
- [ ] https://github.com/Azure/azure-sdk-tools/issues/3475
- [ ] https://github.com/Azure/azure-sdk-tools/issues/3476
- [ ] https://github.com/Azure/azure-sdk-tools/issues/3477
