### ISSUE TITLE
[Perf] Refactor tests.yml into one file per package per language

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk-tools#3530]
Instead of having a single `tests.yml` file with all tests in all languages, the file should be split into one file per package per language:

```
/net/sdk/storage/Azure.Storage.Blobs/perf-tests.yml
/net/sdk/storage/Azure.Storage.Files.DataLake/perf-tests.yml
/java/sdk/storage/azure-storage-blob/perf-tests.yml
...
```

### Tasks
* [x] Make changes to `perf-automation` and `eng/common/perf.yml` to allow pipelines to override the `tests.yml` location.
* [ ] Migrate all pipelines to use `tests.yml` in all language repos
* [x] Run both sync and async by default for .NET, Java, and Python.  JS is async-only, and C++ is sync-only.
* [x] Eliminate "additional-arguments" feature (only used by Java)

### Pros
* Scales better than a single file for all languages and services
* Easier to modify test list for service, including in a PR

### Cons
* No easy way to share code across files, leading to more duplicate code and inconsistencies between services and languages
