### ISSUE TITLE
Standardize engineering tools across repos

### ISSUE THREAD

**Issue by weshaggard** [Azure/azure-sdk-tools#365]
Now that we have a nice public `azure-sdk-tools` repo we should move more of of the internal `azure-sdk-build-tools` stuff into it.  Anything that can be open-sourced should be moved and we should take advantage of the new `eng\common` directory that we automatically sync. 

Some of the stuff in `azure-sdk-build-tools` is also language specific, like some of the release steps, those should probably be put into the language repo's. When we are done the only thing that will likely remain in the `azure-sdk-build-tools` repo are security sensitive tooling/binaries that we shouldn't put into a public repo. 

- [ ] Move most of azure-sdk-build-tools to azure-sdk-tools

**Comment by weshaggard** [comment]
I will do a survey of the stuff we need to move and add a list to this issue and break out other issues if necessary.

**Comment by weshaggard** [comment]
We should move the following parts into the azure-sdk-tools repo:

- [ ] scripts/clean-maven-credentials.ps1
- [ ] scripts/copy-docs-to-blobstorage.ps1
- [ ] scripts/copy-from-azuresdkpartnerdrops.ps1
- [ ] scripts/create-tags-and-git-release.ps1
- [ ] scripts/force-push-to-gh-pages.ps1
- [ ] scripts/git-branch-push.ps1
- [ ] scripts/publish-to-npm.ps1
- [ ] scripts/Submit-PullRequest.ps1
- [ ] tools/blobfeedtool - Assuming we can easily acquire the tools we need, also assuming we don't stop using this tool when we switch to DevOps feeds. 
- [ ] tools/burner-feed
- [ ] tools/generic-blob-upload
- [ ] tools/java-publishing
- [ ] tools/symboltools - Assuming we can easily acquire the tools we need. 
- [ ] pipelines/jobs - Move all
- [ ] pipelines/stages - Move all but refactor out the signing steps and keep them in azure-sdk-build-tools. For the language specific files in here we should put them in the language specific repos. 
- [ ] pipelines/steps - Move all except signing steps. 
- [ ] pipelines/pipeline-generation.yml 

In general everything we that doesn't expose signing tools and secrets or other checked-in binaries should be moved into the azure-sdk-tools repo. 

@mitchdenny can you please have a look over this and let me know if you agree with my assessment about moving these things?

**Comment by mitchdenny** [comment]
Before we do this I want to make sure we aren't jumping into a workflow that is going to make it difficult for us to make changes to the later stages in the pipeline. Today if I want to make changes to the release pipeline this is my workflow:

1. Create a branch in ```azure-sdk-build-tools``` - named ```feature/xyz```
2. Create a branch in the language specific mono repo - named ```feature/xyz```.
3. Update a selection of the ```ci.yml``` files to point to ```refs/heads/feature/xyz```.
4. Modify files across both repos until I've got my desired change.
5. Queue builds manually against the feature branch.
6. Repeat 4-5 until done.
7. Submit PR on azure-sdk-build-tools
8. Remove refs in ```ci.yml``` files.
9. Merge changes to both repos.

This allows me to isolate and test my work with a fairly quick loop time. We'll need to make sure we can do something similar with the sync model. Off the top of my head I think that when someone wants to make changes to common scripts, they'll probably take a branch in the mono repo and modify the files there (instead of ```azure-sdk-tools```) and then once they've got their change working then copy them across to a PR on ```azure-sdk-tools```.

We wouldn't want to try and loop through the sync process every time we made changes, especially knowing how many times we have to tweak things before they are right.

To answer your question though, I think that list above is fine. For the ```java-publishing.yml``` template we'll need to figure out how we want to handle GPG signing. I think moving to a secret file in the pipeline would probably be OK. We should also talk to the ESRP folks about how they want signing to work on increasingly open source projects.

When we first started looking at unified pipelines, one of the things that I suggested was an outboard pipeline that could kick off, do its bit and then copy the outputs back to the originating pipeline, thus keeping the signing process secret.

**Comment by mitchdenny** [comment]
The other thing we should think about here is how do we want to land a change that is this big. I think this is going to be very disruptive so it would be good if we could figure out a way to break it up.

**Comment by weshaggard** [comment]
I use a similar workflow but I often find I need another step as well which is to change the clone-build-tools.yml file to point at my azure-sdk-build-tools branch as well in order to pick-up any non-yml files in my azure-sdk-build-tools changes (i.e. scripts or binaries as part of my change).

I believe I've convinced myself that we can simplify a lot of these common steps with the model of using the eng/common directory, because testing should become as simple as only having one feature branch in the mono language repo for most changes and then once they are ready migrate those changes to the azure-sdk-tools repo. If we do still want or need to test out changes across the different repo's then folks can also create a branch in the azure-sdk-tools repo and we can figure out a way to hook those up so the can be easily tested in other repo's.

>The other thing we should think about here is how do we want to land a change that is this big. I think this is going to be very disruptive so it would be good if we could figure out a way to break it up.

I worry about that as well. I completely agree we need to stage this update correctly and do it incrementally in pieces. Once we get general agreement I will turn this issue into an Epic and break out the work items.

**Comment by mitchdenny** [comment]
OK, that sounds like a strategy. I think the feature branch off each mono repo with manual copying once complete to ```azure-sdk-tools``` will work. And to be honest I'm excited about having a lot of what is in ```azure-sdk-build-tools``` more visible.

Now to peel the onion ;)
