### ISSUE TITLE
APIView: Cross-Language API reviews

### ISSUE THREAD

**Issue by mikekistler** [Azure/azure-sdk-tools#4033]
For DPG generated libraries we need a way to review all the languages together with the Cadl/OpenAPI source used for generation in one ApiView review.

The Cadl/OpenAPI and each language should be shown in separate tabs and switching tabs should maintain context -- meaning that if the user is viewing a particular operation in Python and switches to the Cadl/OpenAPI tab, the content in that tab will be scrolled to the same operation as the Python tab.

We may also want special handling of comments, such as showing comments from all tabs in the OpenAPI/Cadl view (since presumably that's where the changes would be needed).
```[tasklist]
### Tasks
- [ ] https://github.com/Azure/azure-sdk-tools/issues/6889
- [x] Add a link to open full APIView from the cross language view context
- [x] In Cross language View context keep the selected language sticky so user does not have to change it often.
```

**Comment by joshfree** [comment]
@JonathanGiles

**Comment by JonathanGiles** [comment]
I think a way that would work is something like this: you start in the CADL view, you click on some definition, and a right-blade appears with a tabbed interface for each language. In each tab is a fully-fledged APIView, with the selected language-specific code highlighted. This will resolve issues with flicking between tabs, because we never leave the CADL review, and it also means we can see all associated code with the highlighting, even if it is in different parts of the review for each language.

**Comment by maririos** [comment]
Small step in this direction: https://github.com/Azure/azure-sdk-tools/issues/4677

**Comment by maririos** [comment]
Recent APIView deployment includes a step in this direction. See Fro example this review that got created from an APISpec:


![Image](https://user-images.githubusercontent.com/9868623/218834604-47e256e7-4fbe-4d64-8688-8e02821d2b30.png)

**Comment by MrJustinB** [comment]
Phase 1 is complete.  Phase 2 is planned for 1H Gallium

**Comment by maririos** [comment]
This work has stopped until https://github.com/Azure/azure-sdk-tools/issues/8174 and https://github.com/Azure/azure-sdk-tools/issues/5897 are stable

**Comment by maririos** [comment]
Documentation:
- [Cross-Language Definition ID Specification](https://gist.github.com/iscai-msft/600f6b6042753c3f23035a37ebf2a5ae) 
- [Python APIView Cross-Language ID Implementation](https://gist.github.com/swathipil/0da92a2d7a7912fed02788eef5f5fed9)

**Comment by tjprescott** [comment]
This particular item is done since all related issues are done. We have a separate issue for overhauling the cross-language experience as part of a newer issue, in conjunction with the archboard modernization effort.
