### ISSUE TITLE
Admin Dashboard user study and enhancements

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#4045]
1. Dashboard for the Azure SDK team to use to track the state of a Service team on our release process. 

### Phase 1 - Completed
https://github.com/Azure/azure-sdk-tools/issues/5698

**Requirements:** https://microsoft.sharepoint.com/:w:/t/AzureDeveloperExperience/EfvU7xX2ABZNgnL_QVXUpo4Bn05hzV9vhhpZiRZ6MqZIxw?e=SAF2HV

UI: [SDK admin dashboard – Figma](https://www.figma.com/file/F1nFR9MOVml76e7B2eNJiR/SDK-admin-dashboard?node-id=1%3A531&t=aWaVgPrSDBeCkzuJ-0)

### Phase 2 
- [ ] Get user feedback from user studies
- [ ] Capture requirements and prioritize enhancements
- [ ] Evaluate if we need another design/tool to show information

### Phase 3 (possible)
Migrate the Inventory Dashboard to release planner as part of Admin view 

****Associated GitHub issues* that need to be reviewed as potential requirements***

- [ ] https://github.com/Azure/azure-sdk-tools/issues/4136
- [ ] https://github.com/Azure/azure-sdk-tools/issues/3303

**Comment by ladonnaq** [comment]
This is the Azure SDK APEX product dashboard.  Here is draft of the design and use cases - https://microsoft.sharepoint.com/:w:/t/AzureDeveloperExperience/EfvU7xX2ABZNgnL_QVXUpo4Bn05hzV9vhhpZiRZ6MqZIxw?e=SAF2HV.  I am working with Crystal this week on requirements and a new prototype design.  I think that this dashboard lives outside of the release planner because release planner is the service partner home and context is set to a service.   We will want to see all of the release plans.  Please review the draft of the use cases I have identified.  If you have more, please add to the word document.

**Comment by ladonnaq** [comment]
Link to Figma -  https://www.figma.com/file/F1nFR9MOVml76e7B2eNJiR/SDK-admin-dashboard?t=JtFmBtgdkAccEH39-1

**Comment by josefree** [comment]
Add @honghr to assignee. And please note this should be in the scope of 2022 December release scope

**Comment by honghr** [comment]
I reviewed the current UI design and requirement. It's not completed. And more importantly, If we want to show admin dashboard, we need design planner permission first.

**Comment by maririos** [comment]
@ladonnaq @ccbarragan I don't think this work is ready to be reviewd and approved, right?

**Comment by maririos** [comment]
We are going to phase the work needed here so we can start providing value to our team with the information that we are already collecting.
Phase 1 which involves showcasing the raw information in ADO will be part of Gallium

**Comment by ladonnaq** [comment]
We have been gathering and collecting feedback to improve the existing dashboards and ADO queries.  We will close this work item and track any smaller line items as part of this overall epic - https://github.com/Azure/azure-sdk-tools/issues/7822.   The existing dashboard are: 

- Release Planner usage PowerBI Report - https://aka.ms/azsdk/engagement/dashboard
- Scheduling Tool usage PowerBI Report - https://aka.ms/azsdk/engagement/scheduler/dashboard
-  Azure APEX admin ADO dashboard - https://aka.ms/azsdk/apex/dashboard-admin
- Azure SDK Release Plan ADO Dashboard - https://dev.azure.com/azure-sdk/Release/_dashboards/dashboard/055187ac-0c51-4503-b0da-40f196172393
