### ISSUE TITLE
TypeSpec Onboarding Process tracking to identify requirements for Release Apps

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#4050]
The purpose of this requirement is to define the requirements in the release planner app for TypeSpec onboarding via the Release Planner (API readiness).  This requirement is part of the TypeSpec Requirements for the Release Planner epic - https://github.com/Azure/azure-sdk-tools/issues/5619

### Prerequisites 

- [ ] Introduction meeting for API Design & TypeSpec so that we can better understand the APIs that the service team will be designing and provide an overview of the value that TypeSpec will bring.  This also gives a chance for the service team to ask questions and us to provide feedback earlier in the process. **_Blocked by process:_** TypeSpec team and API Stewardship Board would need to own this meeting.  
- [ ] Assign service buddy from TypeSpec to help service partners. **_Blocked by process:_** TypeSpec would need to own assigning a perosn and defining the role. 
- [ ]  Enable API Spec pipeline - https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/606/Enable-API-Spec-Pipeline (This needs to be automated, there are too many manual steps and the current documentation is confusing - see this GitHub issue https://github.com/Azure/azure-sdk-tools/issues/5161)
- [ ] Ensure users has all permissions for tooling around TypeSpec (GitHub? )
- [ ]Installation for TypeSpec-  https://azure.github.io/cadl-azure/docs/getstarted/installation

        - It is not clear from reading the docs page if the user must install the cadl core toolset before installing the Azure cadl toolset or if it is optional.  There are multiple options it seems for installing and using Cadl. Docker, locally, VS Code extensions, ...  We should present these options and explain any pros/cons.  

![image](https://user-images.githubusercontent.com/67656762/213290026-28c39a05-f745-4e41-8a6a-8982d42b853c.png)

**Comment by josefree** [comment]
I place the milestone to be '2023-01'. This could be closed when Release Planner can cover both Data Plane and Management Plane SDK release.

**Comment by ladonnaq** [comment]
@mikekistler This is also one of the topics we did not get to yesterday during our meeting.  I am assigning to you so we can figure out the process and any requirements for the release planner or scheduling tool.  I will setup a meeting for us to walk through next week.

**Comment by ladonnaq** [comment]
This is the current screens in the API readiness application that are attempting to provide information to the service partner on what they need to do to onboard and get started with Cadl.  
**Feedback from stakeholder review:** 
- The documentation for the enabling the API Spec pipeline is overwhelming.  It is not clear if this is for management plane and data plane. Is it possible to automate this step or provide simpler instructions?  
- The screen ask the user to confirm Cadl is up and running but at this point Cadl has never been introduced to the user.  There is also no step to have the user complete the installation for Cadl.  
- There are other issues with these 2 screens but I will open different GitHub issues since they are not related directly to Cadl. 

![image](https://user-images.githubusercontent.com/67656762/212208658-bddef4ce-a6b6-4b47-ab3e-98012e656e85.png)

![image](https://user-images.githubusercontent.com/67656762/212208709-9e0afde8-7ab5-4d04-8026-0b65d92eaefe.png)

**Comment by ladonnaq** [comment]
These requirements are no longer relevant.  At this point, there is no requirement for a TypeSpec onboarding meeting, engineering is manually adding the TypeSpec onboarding buddy to the product ADO epic work item, API Spec pipeline for early API validation has been suspended because it was a manual process requiring many steps to complete (very time consuming for the service partners).
