### ISSUE TITLE
APIView Memory and Performance

### ISSUE THREAD

**Issue by chidozieononiwu** [Azure/azure-sdk-tools#4233]
Identify and resolve memory and performance issues in APIView. Specifically large review pages.
```[tasklist]
### Tasks
- [ ] Identify and resolve problem affecting Interaction To Next Print https://web.dev/articles/inp
- [x] Look into using HTTP caching.
- [x] Look into Enabling Content Compression
- [ ] CDN  for Images
```

**Comment by JonathanGiles** [comment]
If this is fixed, it would be good to remove the 'show documentation' checkbox and load it all the time, so that documentation can be easily expanded / collapsed whenever necessary, without first showing documentation.

**Comment by chidozieononiwu** [comment]
> If this is fixed, it would be good to remove the 'show documentation' checkbox and load it all the time, so that documentation can be easily expanded / collapsed whenever necessary, without first showing documentation.

I think we are good to turn on show documentation. Here is an example https://apiview.dev/Assemblies/Review/769eefa2cf1a415aa8b0456475efaf1c/5950731341f24d25a679b54bc7660222?doc=True&diffOnly=False

**Comment by maririos** [comment]
Not sure that is true in all cases. I just tried loadidng the comments here: https://apiview.dev/Assemblies/Review/1a3f80ba464848fc953beddb4e282ee9/076e03c2d1d74ceabd4c746f386a0183?doc=True&diffOnly=False and APIView crashed

**Comment by chidozieononiwu** [comment]
Oh I see so we still need to implement lazy loading to handle this extra long cases.
