### ISSUE TITLE
SDK Release Process Documentation - redesign and migrate to Engineering Hub 

### ISSUE THREAD

**Issue by MrJustinB** [Azure/azure-sdk-tools#4425]
This is to capture the epic for updating the wiki documentation:

1.  move it out of the internal DevOps space (to Eng Hub?)
2. Review for accuracy
3. Update out of date content
4. Consolidate duplicative content
5. Update to account for the new Release Planner tool
6. Improve content organization and usability
7. Reference documentation from within the Release Planner

Associated GitHub issues related to release planner documentation (outbound documentation needed): 

- [x] https://github.com/Azure/azure-sdk-tools/issues/5989
- [x] https://github.com/Azure/azure-sdk-tools/issues/6083
- [ ] https://github.com/Azure/azure-sdk-tools/issues/4451
- [x] https://github.com/Azure/azure-sdk-tools/issues/5628

**Comment by ccbarragan** [comment]
#### Kick-off meeting notes (10/26)
Attendees:  Crystal, Justin, LaDonna, Wes, Mariana
[Link to FigJam](https://www.figma.com/file/5BrrsqEa38u0inImqk29AD/SDK-onboarding-docs-brainstorm?node-id=1%3A161)

- Discussed the overall context and goals for this docs effort
  - **User story:** As a service partner, I want access to up-to-date docs that can help me as I onboard with the Azure SDK team.
  - **Pain point themes:**
     - Missing access / permissions. We have some internal docs in private repos (both on ADO and GitHub) that aren't accessible by some service teams.
     - Not centralized. Today, service teams go to our internal wikis, azure.io, archboard docs, and API stewardship docs to find the information they're looking for. 
  - **Goals**
    - Organize, update, consolidate the information in a central place that is easily accessible by Azure service teams
    - Ensure there's a consistent audience for this content (these should be docs that are meant primarily for service partners and not for our own internal teams)
    - Keep the contribution process light. If possible, put docs close to where folks are already working (less friction to contribute)

- Next steps
   - Reclaim the old Azure SDK Engineering Hub space
   - Audit existing service partner content
   - Start to map out a content structure / IA (keeping release planner in mind)

**Comment by ccbarragan** [comment]
**Status update (4/17)**

- Reclaimed the old Engineering Hub docs space -- commits to the repo are now generating on the docs site as expected.
- Completed a docs audit of existing partner content
- (In progress) Working towards content structure and placeholders in Engineering Hub. Issue: https://github.com/Azure/azure-sdk-tools/issues/5989

**Comment by maririos** [comment]
@ccbarragan do you consider we can close this epic?

**Comment by ccbarragan** [comment]
Yes! Updates:

- [9/1] Announced new Engineering Hub site by posting on the [Azure SDK General Teams channel](https://teams.microsoft.com/l/message/19:f6d52ac6465c40ea80dc86b8be3825aa@thread.skype/1693584021615?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1693584021615&teamName=Azure%20SDK&channelName=General&createdTime=1693584021615) and PM newsletter.
- Docs retirement plan in place to remove old / deprecated docs on January 2024.

Closing.
