### ISSUE TITLE
How to handle extensions in Azure SDK Release Planner

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#4537]
If a product needs more time to complete an Azure SDK launch criteria, they can request an extension.  

- [ ] Link to Azure SDK extension wiki page -  https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/644/Azure-SDK-Extension-Process-(previously-known-as-signoff-with-exception)
- [ ] The extensions are tracked in the Azure Devops onboard work items.  
- [ ] There is a query tile on the Azure Devops APEX dashboard for data plane and management plane.  https://dev.azure.com/azure-sdk/Release/_dashboards/dashboard/d7d93c77-6201-43a4-a17f-434cc8e71c6b
- [ ] 
![image](https://user-images.githubusercontent.com/67656762/198377575-756d4b59-2a15-4c16-b55d-54ede2806d2f.png)

- [ ] The Release Planner app needs to provide information and update the Azure Devops work item for extensions.  
- [ ] Most extensions are related to the Public Preview or GA SDK Release Readiness.  The most frequent extension are:  non-RPaaS products with swagger KPI error that need to be resolved for new API versions and extension to release all or language specific SDKs after the launch date.  

```[tasklist]
### Tasks
- [ ] https://github.com/Azure/azure-sdk-tools/issues/6597
- [ ] https://github.com/Azure/azure-sdk-tools/issues/5503
```

**Comment by maririos** [comment]
Will this requirement be covered in the UI changes that @ccbarragan is working on?

**Comment by ladonnaq** [comment]
> Will this requirement be covered in the UI changes that @ccbarragan is working on?

@maririos Yes it should be a requirement for the new UI.  We need to decide where and how service teams can raise request for extensions.

**Comment by maririos** [comment]
It was agreed that while this work starts, @ladonnaq  is going to update the documentation to amke sure people know what work around to use

**Comment by ladonnaq** [comment]
@maririos I am closing this issue and created a new one that will track the work we will do this semester for extensions. https://github.com/Azure/azure-sdk-tools/issues/7913
