### ISSUE TITLE
Arch Board Intro Meeting - Release Planner App and Scheduling Tool Integration 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#4598]
The Introduction to the Azure Developer Experience Architecture Board meeting should be a requirement for a service or a product that will be releasing new initial client libraries (and SDKs).  For example, new Cognitive Services products are skus.  These skus typically have a new API which will result in new client libraries which will be added to the Cognitive Services SDKs. 

@live1206  @maririos - Here are my suggested changes for the current version of the SDK Release app for the Intro/SDK Review meeting. We will address any additional feedback in the new UI.  

### Functional Requirements
- [x] The Introduction meeting is required for the following scenarios:  new initial Beta SDK release. This should cover new services with no existing SDKs and Services with existing SDKs but adding new client libraries (i.e. new Cognitive product).  
- [x] Release planner will check to see if release plan is for new initial beta SDK for data plane.  If YES then pass info to scheduling tool so that the default meeting type is "Introduction".  If NO, then default meeting type is "SDK Review".  

### UI Requirements

- [x] Move Schedule Arch Board Meeting (first step in the Generate SDK Code and Write Test section) 
![image](https://user-images.githubusercontent.com/67656762/219490262-a5743b67-b003-438d-af4e-d84cf89f1955.png)
**Changes to the Schedule Arch Board meeting screen/blade.**  

- [x] Change text and move it to above the table. Conditional statements based on if initial beta or initial stable.  @kyle-patterson @ronniegeraghty What about new SDK versions?  What kind of Arch Board review is required?  
- [x] Change Review required artifacts to "Review or update required artifacts".   The link should be to the scheduled meeting so that they can review or updates the fields in the scheduler for Intro or SDK Review meeting.  

![image](https://user-images.githubusercontent.com/67656762/219504591-02587ab2-dc08-49f1-be4d-aa033441a963.png)

**Comment by ladonnaq** [comment]
@kyle-patterson @ronniegeraghty Please confirm scenarios that require Azure SDK Intro sessions by default.  The release planner can include this as a step and the scheduling tool can pop-up pre-populated with all of the information we have gathered so far.  Support would be for Cadl + DPG first but we could also support for other scenarios if we can clearly identify the scenarios. For example, if a service partner has a new API (not a new API version) that will result in new client libraries, then should there be a service intro for this new API.

**Comment by ladonnaq** [comment]
Design and requirements as follow based on discussions with Ronnie, Kyle, and the arch board members who participated in the arch board admin meeting (scheduled by Ronnie and Klye). 

1. New pre-requisite for arch board introduction meeting.  This should invoke the scheduling tool to schedule the introduction meeting.  
2. This should be done as a pre-requisite and on a different blade than the current one below. 

![Image](https://user-images.githubusercontent.com/67656762/206278479-79555a7c-1221-45ae-a5d1-2db390e489cb.png)
3. New blade should preview the prerequisites for the Introduction meeting with the opportunity for user to provided links.  

- [ ] Hero/Champion scenario (link)
- [ ] Overview of the service or product associated with the new initial SDK releases (link) 
- [ ] Samples (can be pseudocode) (link) 
- [ ] Generated SDKs and APIViews (links in a table similar to below) 

![Image](https://user-images.githubusercontent.com/67656762/206279640-b443700e-7075-43fe-8b94-7102df26a2ae.png)

- [ ] Prompt to schedule the Introduction meeting with the architecture board (invokes the scheduling app).  Should be greyed out until all prerequisites are provided. 
4. Scheduling Tool Requirements 

- [ ] Include prerequisite data in the scheduling app and ensure that only Introduction meeting type is enabled. 
- [ ] Ensure that all of the data is prerequisite data is in the GitHub issue that is created by the scheduling app.  
@ronniegeraghty @kyle-patterson Is there a specific GitHub issue template that the scheduling app should use/look at for the Introduction meeting?  Are there any labels or any additional information you want in the GitHub issue? 
5. @ronniegeraghty @kyle-patterson How will the release planner app know that the Introduction meeting has been completed?  
6. Add the Introduction with Arch Board as a requirement for SDK release readiness.  This blade should include all related SDK release readiness criteria, including the introduction meeting. 


![Image](https://user-images.githubusercontent.com/67656762/206281060-ef9c30e5-50d0-4508-852e-f9d2e1442644.png)

**Comment by maririos** [comment]
@ladonnaq 
Clarifying questions:

>> 3. New blade should preview the prerequisites for the Introduction meeting with the opportunity for user to provided links.

> - Hero/Champion scenario (link)
> - Overview of the service or product associated with the new initial SDK releases (link)
> - Samples (can be pseudocode) (link)
> - Generated SDKs and APIViews (links in a table similar to below)

- These prerequistes are different than the ones present in the documentation here: https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/667/Azure-SDK-Archboard-Review?anchor=informational-meeting
We need to make sure that names and types of documents are the same between tools and documentation. Which one do you want to use? Or should the documentation be updated?

- Any reason to ask for the prerequisites in the `Data Plane SDK Release App` and not in the `Scheduler App`?
- For Generated SDKs and APIViews => Is the idea to go to the Introduction meeting with the SDK generated from the API Spec PR that was approved by the API Board? So looking at the Apps, this means the `Data Plane API Readiness` app like you show?
  - If we already have them, we should populate the requisites with this information instead of asking the user, right?

- APIView has the ability for the user to upload samples (example) so we can ask the users to use that instead of uploading a new file for us to mantain. What do you think?
<img width="389" alt="image" src="https://user-images.githubusercontent.com/9868623/206576440-d3f65b07-dc4a-44d5-9a26-290bcc4de7e9.png">

>> 4. Scheduling Tool Requirements
> - Ensure that all of the data is prerequisite data is in the GitHub issue that is created by the scheduling app.
@ronniegeraghty @kyle-patterson Is there a specific GitHub issue template that the scheduling app should use/look at for the Introduction meeting? Are there any labels or any additional information you want in the GitHub issue?

The GitHub issue createad already includes all the information we collect from the Scheduler App. If the pre-requisites changed (above conversation) then we will modify this too. 
Example:
<img width="399" alt="image" src="https://user-images.githubusercontent.com/9868623/206577468-a814dca3-fb73-41b1-adcf-4f237a0bef6e.png">

**Comment by maririos** [comment]
I forgot to add, the idea to include the APIViews in the introduction meeting is to review the APIs? do we want the architects to comment in those APIViews?
If so, then how is this different than a follow up Arch board? should we wait until the service actively works on the SDKs that are generated in the following steps (2) of the `Data Plane SDK Release` ?

**Comment by ladonnaq** [comment]
> @ladonnaq Clarifying questions:
> 
> > > 3. New blade should preview the prerequisites for the Introduction meeting with the opportunity for user to provided links.
> 
> > * Hero/Champion scenario (link)
> > * Overview of the service or product associated with the new initial SDK releases (link)
> > * Samples (can be pseudocode) (link)
> > * Generated SDKs and APIViews (links in a table similar to below)
> 
> * These prerequistes are different than the ones present in the documentation here: https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/667/Azure-SDK-Archboard-Review?anchor=informational-meeting
**_(La Donna) I was looking at the GitHub page for the arch board introduction meeting - https://azure.github.io/azure-sdk/policies_reviewprocess.html.  These requirements are not the same a found on the wiki page. (Copied screenshot below)._** 

>   (Mariana) We need to make sure that names and types of documents are the same between tools and documentation. Which one do you want to use? Or should the documentation be updated?

 _@ronniegeraghty  @kyle-patterson - What are the expectations for prerequisites the service partner needs to have completed and provide during the Introduction to the Arch Board meeting?  Once you have decided, would you please update the wiki and GitHub page so that the information is consistent?_ 

![image](https://user-images.githubusercontent.com/67656762/207476760-062f1a43-8907-4d83-835d-36288531b498.png)


> * Any reason to ask for the prerequisites in the `Data Plane SDK Release App` and not in the `Scheduler App`?
> * For Generated SDKs and APIViews => Is the idea to go to the Introduction meeting with the SDK generated from the API Spec PR that was approved by the API Board? So looking at the Apps, this means the `Data Plane API Readiness` app like you show?
****(La Donna)  The initial Data Plane API Readiness should be complete before entering SDK Release. I would expect that we would store the links to the any completed assets of the Data Plane API Readiness milestone.  This would include Hero Scenarios, the generated APIViews, generated SDKs, etc.  The samples are not requested in the Data Plane API Readiness app, so we would need to ask for those.  I do think that we should make sure that the service partner has completed all pre-requisites before scheduling the Introduction Meeting.  This would mean that we may want to have a blade for scheduling the Introduction meeting that shows all of the pre-requisites and if we have data, it would be on the blade.****  
>    
>   * If we already have them, we should populate the requisites with this information instead of asking the user, right?
> * APIView has the ability for the user to upload samples (example) so we can ask the users to use that instead of uploading a new file for us to mantain. What do you think?
**(La Donna) Perfect!** 
> 
> <img alt="image" width="389" src="https://user-images.githubusercontent.com/9868623/206576440-d3f65b07-dc4a-44d5-9a26-290bcc4de7e9.png">
> 
> > > 4. Scheduling Tool Requirements
> > 
> > 
> > 
> > * Ensure that all of the data is prerequisite data is in the GitHub issue that is created by the scheduling app.
> >   **

> @ronniegeraghty @kyle-patterson Is there a specific GitHub issue template that the scheduling app should use/look at for the Introduction meeting? Are there any labels or any additional information you want in the GitHub issue?

> 
> The GitHub issue createad already includes all the information we collect from the Scheduler App. If the pre-requisites changed (above conversation) then we will modify this too. Example: <img alt="image" width="399" src="https://user-images.githubusercontent.com/9868623/206577468-a814dca3-fb73-41b1-adcf-4f237a0bef6e.png">

**Comment by ladonnaq** [comment]
@ronniegeraghty @kyle-patterson We need your feedback so that engineering can work on the implementation for this epic/feature.  We will begin piloting the release planner with service partners in scope for Cadl + DPG in January.  If we are not prompting the service partner when to schedule the Introduction within the release planner, then they will not schedule the meeting and that will be problematic.

**Comment by maririos** [comment]
@ladonnaq thank you for the clarifications :) I will wait on Kyle and Ronnie for the open questions:
- prerequissites:
- (previously posted) I forgot to add, the idea to include the APIViews in the introduction meeting is to review the APIs? do we want the architects to comment in those APIViews?
If so, then how is this different than a follow up Arch board? should we wait until the service actively works on the SDKs that are generated in the following steps (2) of the Data Plane SDK Release ?

**Comment by ladonnaq** [comment]
@kyle-patterson @ronnie - How does an Intro meeting for Cadl + DPG differ from other Intro meetings?   From discussions with the arch board, it seems they do want an intro meeting for services that are bringing forward new APIs (likely associated with a new product).  

Is this list valid?  Anything missing?  

- [ ] APIViews (should already be generated from the PR for the new Cadl/API) 
- [ ] Charts/Info in the new service/product 
- [ ] If the new service/product has a name, then naming approval for namespace for each language 
- [ ] Hero/Champion scenario 


Would a follow-up meeting be a specific topic?  For example, follow-up Java and JavaScript SDK review.  Or follow-up for naming approval for Python.

**Comment by live1206** [comment]
@maririos Please let me know once you finalize the missing information from Release Planner App.

@ladonnaq Should this issue belong to `Scheduler Tool` instead of `Release Planner`?

**Comment by maririos** [comment]
> @maririos Please let me know once you finalize the missing information from Release Planner App.

@live1206 I am still waiting for PM feedback on the information to include in a meeting and the Wiki to link to. But from what I see, I don't expect too much work to happen on the Scheduler Side.

For `Release Planner` the work will be to add a step in one fo the apps that will prompt the Intro meeting. 
As for scheduling a follow up, maybe the release planner should have that logic and let the scheduler meeting know the type.

**Comment by ladonnaq** [comment]
> > @maririos Please let me know once you finalize the missing information from Release Planner App.
> 
> @live1206 I am still waiting for PM feedback on the information to include in a meeting and the Wiki to link to. But from what I see, I don't expect too much work to happen on the Scheduler Side.
> 
> For `Release Planner` the work will be to add a step in one fo the apps that will prompt the Intro meeting. As for scheduling a follow up, maybe the release planner should have that logic and let the scheduler meeting know the type.

I updated the description for the requirements for the current release planner.  We will address any new or additional feedback in the new UI.  I also hid all of the other comments so that it will be less confusing.

**Comment by zzvswxy** [comment]
For  Data plane SDK release type = "new initial client libraries, no existing SDKs for service" or "new initial client libraries, existing SDKs for service"
![image](https://user-images.githubusercontent.com/20081898/219578114-b9ffa6a2-63dc-4b04-adcf-e36fcc44571a.png)

For  Data plane SDK release type = "new version of client libraries, new SDK version"
![image](https://user-images.githubusercontent.com/20081898/219577446-9bbf94fd-356a-44c4-8e12-1693548a7b4b.png)

CC @maririos 
As we move Schedule Arch Board Meeting to first step in the Generate SDK Code and Write Test section. We will not write SDK apiView info to the Artifacts table. The SDK apiView will be generated in Grow Up SDK  step, and then the service team can review or updates the fields in the scheduler for Intro or SDK Review meeting.

**Comment by maririos** [comment]
@zzvswxy sounds good. If the user is not going to be blocked on generating the SDKs because they haven't had the archboard, then I agree

**Comment by zzvswxy** [comment]
deployed to Prod
