### ISSUE TITLE
Enable accessibility features for all of our Power Apps 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#4776]
We ensure that our Power Apps are accessible.  We should use the accessibility checker first to determine the current state of the applications.  Then we can create GitHub issues and prioritize.  We should add a category for accessibility that can be used for all of the GitHub issues that are related to accessibility.  

Resource List: 

- https://learn.microsoft.com/en-us/power-apps/maker/canvas-apps/accessibility-checker
- https://learn.microsoft.com/en-us/power-apps/maker/canvas-apps/accessible-apps-limitations
- https://learn.microsoft.com/en-us/power-apps/maker/canvas-apps/controls/properties-accessibility
- https://learn.microsoft.com/en-us/power-apps/maker/canvas-apps/accessible-apps
- https://learn.microsoft.com/en-us/power-apps/maker/canvas-apps/accessible-apps-structure
- https://learn.microsoft.com/en-us/power-apps/maker/canvas-apps/accessible-apps-color
- https://learn.microsoft.com/en-us/power-apps/maker/canvas-apps/accessible-apps-content-visibility
- https://learn.microsoft.com/en-us/power-apps/maker/canvas-apps/accessible-apps-live-regions

**Comment by josefree** [comment]
bring this to engineering triage

**Comment by JonathanCrd** [comment]
I splitted the work that has to be done here in several issues:

```[tasklist]
### Tasks
- [ ] https://github.com/Azure/azure-sdk-tools/issues/7513
- [ ] https://github.com/Azure/azure-sdk-tools/issues/7514
- [ ] https://github.com/Azure/azure-sdk-tools/issues/7515
```

**Comment by MrJustinB** [comment]
Closing this is not a priority now. We can reopen if we determined it is a priority in the future
