### ISSUE TITLE
Unify Index Generation [github.io]

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-tools#480]
The github.io indexes are generated with individual implementations in each repository.

There is _nothing_ language specific about index. `docfx` or `typedoc` or `sphinx` _do not matter_ as there is no reference documentation being generated inside the index. The index is simply a set of landing pages. The real reference documentation lives in blob storage.

Instead, what really matters is that there is:

1. A `service mapping` that maps package locations/ids to a friendly service name
2. A common script that can generate landing pages for all discovered services/packages in a target repository

Ideal world will be to check these common generation scripts into azure-sdk-tools and provide the skin (JS, CSS, HTML templates) from within the specific language repos. 

This issue covers both the common code as well as the adjustments to CI to allow the new methodology to be used.

- [ ] Java
- [ ] JS
- [ ] Python
- [ ] .NET
- [ ] C

Tasks:
- [x] https://github.com/Azure/azure-sdk-tools/issues/917 Have language specific stuff in Language-setting.ps1
- [x] https://github.com/Azure/azure-sdk-tools/issues/1120 Restructure on release data of c repo
- [x] https://github.com/Azure/azure-sdk-tools/issues/1121 Clean up C documentation on blob storage

**Comment by kurtzeborn** [comment]
Converting this into an epic since this represents a chunk of work all on it's own.  And wasn't really part of our initial plans for github.io vNext.

**Comment by sima-zhu** [comment]
- [ ] https://github.com/Azure/azure-sdk-tools/issues/1120 Restructure on release data of c repo

**Comment by sima-zhu** [comment]
- [ ] https://github.com/Azure/azure-sdk-tools/issues/1121 Clean up C documentation on blob storage

**Comment by sima-zhu** [comment]
The common scripts is in tool PR: https://github.com/Azure/azure-sdk-tools/pull/1151/files

**Comment by sima-zhu** [comment]
- [ ]  Move common thing to eng/common

**Comment by sima-zhu** [comment]
- [ ]  https://github.com/Azure/azure-sdk-tools/issues/1224 Add display name on github io page.

**Comment by weshaggard** [comment]
@sima-zhu lets also add a item to make sure that the pipeline names all match once you get the yml file under eng/common.

**Comment by sima-zhu** [comment]
- [ ] https://github.com/Azure/azure-sdk-tools/issues/1246 Align all lang blob storage path.

**Comment by sima-zhu** [comment]
- [ ] https://github.com/Azure/azure-sdk-tools/issues/1248 Change the copy-docs-blob-storage scripts to adopt the c documents.

**Comment by sima-zhu** [comment]
- [ ] https://github.com/Azure/azure-sdk-for-net/pull/17400 https://github.com/Azure/azure-sdk-tools/pull/1257 Update .NET blob storage path

**Comment by sima-zhu** [comment]
The epic is resolved.
