### ISSUE TITLE
Review content for Release Planner

### ISSUE THREAD

**Issue by ccbarragan** [Azure/azure-sdk-tools#4857]
Review existing content for Release Planner.

**Success criteria**

- Content is organized logically with localization in mind
- Terminology is reviewed for clarity
- Content meets Microsoft writing guidelines

**Tasks**

- [x] Review all screens in Release Planner
- [x] Review updates with team
- [x] Hand-off to dev for updates in Power Apps

**Links**
[Link to Power Apps](https://apps.powerapps.com/play/e/ca95f761-477a-4e98-b34e-dfd5dd03a770/a/ece65a45-f966-4d8b-b04a-24329c5b8e99?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47)

**Comment by ccbarragan** [comment]
Initial review of content completed in Power Apps prototype: https://apps.powerapps.com/play/e/ca95f761-477a-4e98-b34e-dfd5dd03a770/a/ece65a45-f966-4d8b-b04a-24329c5b8e99?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47
