### ISSUE TITLE
[ApiView] Improvements to Swagger Pages

### ISSUE THREAD

**Issue by chidozieononiwu** [Azure/azure-sdk-tools#4864]
Using this to track further improvement requested in swagger pages

```[tasklist]
### Tasks
- [ ] https://github.com/Azure/azure-sdk-tools/issues/4779
- [ ] https://github.com/Azure/azure-sdk-tools/issues/4780
- [ ] https://github.com/Azure/azure-sdk-tools/issues/4749
- [ ] https://github.com/Azure/azure-sdk-tools/issues/4978
- [x] https://github.com/Azure/azure-sdk-tools/issues/4496
- [ ] https://github.com/Azure/azure-sdk-tools/issues/6008
- [ ] https://github.com/Azure/azure-sdk-tools/issues/6254
- [ ] https://github.com/Azure/azure-sdk-tools/issues/6296
- [ ] https://github.com/Azure/azure-sdk-tools/issues/5582
- [ ] https://github.com/Azure/azure-sdk-tools/issues/6188
- [ ] https://github.com/Azure/azure-sdk-tools/issues/6259
```
