### ISSUE TITLE
Redesign of the API Readiness Signoff Screen 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#4905]
Redesign data plane and management plane API Readiness Screen to provide better clarity to the information and actions associated with this screen. 

- [x] @josefree @maririos Is there any tooling that checks for potential breaking changes between different version of Cadl and/or the generated OpenAPI doc for data plane?  If so, will an initial breaking change review be done and approved during the API Review as is done in management plane.  Or is this only done at the time of the SDK Reviews for data plane?  
- ~~I think we should eliminate the "Complete" button and just make the main user action be "review API readiness validation status", when ready submit API Readiness validation (checkbox) for signoff.~~ 
- [x] When the box is checked, the following Azure Devop onboard work item fields need updated. 
![image](https://user-images.githubusercontent.com/67656762/215845688-d1c453f2-3f0a-46a8-8f8e-8755d4af075a.png)
![image](https://user-images.githubusercontent.com/67656762/215845867-0bef956d-91b5-4dce-84a4-d4ae472b09d6.png)

- [x] Updated layout/info for the API readiness validation screen. Make it look like management plane but no SDK breaking changes.

**Comment by ladonnaq** [comment]
We have additional feedback from the user study with the stakeholders.  We need to redesign UI and backend.

**Comment by maririos** [comment]
> @josefree @maririos Is there any tooling that checks for potential breaking changes between different version of Cadl and/or the generated OpenAPI doc for data plane? If so, will an initial breaking change review be done and approved during the API Review as is done in management plane. Or is this only done at the time of the SDK Reviews for data plane?

There is tooling for breaking changes on OpenAPI files. The API Stewardship board won't approve a PR if this validation fails so I don't think we should mention it in this view.

For Cadl currently we don't have that tool, but the Cadl team is working on having one and eventually integrating it into the PR. Same as OpenAPI.

I don't believe we have a tool that will check that the generated SDKs don't have breaking changes.

**Comment by josefree** [comment]
> I think we should eliminate the "Complete" button and just make the main user action be "review API readiness validation status", when ready submit API Readiness validation (checkbox) for signoff.

When user clicks the button "Complete", at the backend, it marks the milestone of API Readiness complete, so that user can move onto the next milestone.

**Comment by josefree** [comment]
Let's revisit the issue when CADL breaking change validation tool is available.

**Comment by josefree** [comment]
And need also take a reference to design idea collected in https://github.com/Azure/azure-sdk-tools/issues/5157

**Comment by ladonnaq** [comment]
> Let's revisit the issue when CADL breaking change validation tool is available.

When will the Cadl breaking change validation tool be available for testing?

**Comment by live1206** [comment]
The Cadl breaking change review is part of Cadl validation tool, it's expected to be ready next week.
There is no change required in Power Apps.

**Comment by live1206** [comment]
@ladonnaq Please provide the text for signoff page above complete button.
Dev will update ADO work item fields upon comletion.

**Comment by live1206** [comment]
> When the box is checked, the following Azure Devop onboard work item fields need updated.

- When data-plane private preview release plan is complete, set "Data Plane API Readiness" in ADO to `Complete`
- When management-plane private preview release plan is complete, set "Mgmt API Validation Private Preview" in ADO to `Complete`

@ladonnaq For data-plane public preview release plan completion, should we set "Data Plane Beta SDK Release Readiness" in ADO to `Complete` and management-plane public preview release plan complete, set "Mgmt PubPrev SDK Readiness" to `Complete`. Same goes for GA as well?

**Comment by live1206** [comment]
> > When the box is checked, the following Azure Devop onboard work item fields need updated.
> 
> * When data-plane private preview release plan is complete, set `Data Plane API Readiness` in ADO to `Complete`
> * When management-plane private preview release plan is complete, set `Mgmt API Validation Private Preview` in ADO to `Complete`
> 
> @ladonnaq For data-plane public preview release plan completion, should we set `Data Plane Beta SDK Release Readiness` in ADO to `Complete` and management-plane public preview release plan complete, set `Mgmt PubPrev SDK Readiness` to `Complete`? And same thing applies for GA releases.

Will update the status in ADO for Public Preview and GA as well

**Comment by live1206** [comment]
- "REST API state" for public preview data-plane api readiness
- "Data Plane Beta SDK Release Readiness Launch Criteria" for public preview data-plane sdk release
- "Stable API readiness state" for GA data-plane api readiness
- "Data Plane Stable SDK Release Readiness" for GA data-plane sdk release
- "Mgmt PubPrev API readiness" for public preview management-plane api readiness
- "Mgmt PubPrev SDK Readiness" for public preview management-plane sdk release
- "GA Swagger State" for GA sdk release

**Comment by maririos** [comment]
Are those properties on ADO and when they should be used or updated in the Release Planner App?
Does this documention exist somewhere? or should we add it to the wiki so in the future we know where to look and make the correlation?

**Comment by ladonnaq** [comment]
> Are those properties on ADO and when they should be used or updated in the Release Planner App? Does this documention exist somewhere? or should we add it to the wiki so in the future we know where to look and make the correlation?

They is a table in the design docs we created earlier.  I can copy the table to a wiki and we can keep it there. It can be confusing. Remember the field name in ADO does not always match the label name that you see on a work item. You have to look at the template to get the field names.

**Comment by ladonnaq** [comment]
> * "REST API state" for public preview data-plane api readiness
> * "Data Plane Beta SDK Release Readiness Launch Criteria" for public preview data-plane sdk release
> * "Stable API readiness state" for GA data-plane api readiness
> * "Data Plane Stable SDK Release Readiness" for GA data-plane sdk release
> * "Mgmt PubPrev API readiness" for public preview management-plane api readiness
> * "Mgmt PubPrev SDK Readiness" for public preview management-plane sdk release
> * "GA Swagger State" for GA sdk release

I will copy the table we had in the design document that identifies the ADO field name, field label in work item, value.  Remember you have to look at the template for the onboard work item because the field name does not always match the label name (what you see on the onboard work item that is created).

**Comment by live1206** [comment]
I got these fields from ADO settings, they're not the display names, they're the fields ids.

**Comment by maririos** [comment]
Great! could we add them to https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/832/Release-Planner-App

**Comment by live1206** [comment]
The actual ids can be found in the Power Apps code, I am trying to list test scenarios for Release Planner since we are getting more functionalities. And these ADO fields verification will be covered in the test cases.
