### ISSUE TITLE
Release Planner V2 Usability 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#5041]
### Completion of UI content review (owned by Crystal)

- [x] Crystal’s target is to have UI content review done Friday.  
- [x]  Ensure stakeholder feedback regarding UI has been addressed (i.e. grammar, semantics, word choices, …) as part of UI content review. @ccbarragan Would you please reference our Notes & Observations to make sure that the stakeholder feedback is addressed in the UI content review? 
- [ ]  @ccbarragan What is your plan for reviewing your findings from the UI content review with the Release Planner team?  
- [ ]  @ccbarragan What is target date for creating and prioritizing the GitHub issues related to the UI content review?  

### Share initial stakeholder feedback with the Release Planner V2 with engineering team. 

- [x] Crystal and I plan to meet with Kyle and Ronnie this week so that we can get additional feedback on the Data plane SDK release application.  After we speak to them, I believe we have enough feedback to share with the engineering team for the current version of the release planner, Data PlaneAPI readiness, and Data Plane SDK Release apps.   
- [x] [Stakeholder Notes & Observations](https://microsoft.sharepoint.com/:fl:/s/a8deefde-7c82-4dbf-98e1-5238b2c9e016/ET4hmEPwJ-JHv1jwLMgPh7cB6bBvqok2k6Ba4zxT9Ib5Tg?e=7VhdtF&nav=cz0lMkZzaXRlcyUyRmE4ZGVlZmRlLTdjODItNGRiZi05OGUxLTUyMzhiMmM5ZTAxNiZkPWIhLXhNU1pGQnBka3lvUkdNaG1nMV9odXNDMnJFUVNqZElqcGpPLWdYVG1vYUh1SVlIRWZDdFJaLWhMTVliZmhpaCZmPTAxQk9RNk4zSjZFR01FSDRCSDRKRDM2V0hRRlRFQTdCNVgmYz0lMkYmZmx1aWQ9MSZhPUxvb3BBcHAmcD0lNDBmbHVpZHglMkZsb29wLXBhZ2UtY29udGFpbmVyJng9JTdCJTIydyUyMiUzQSUyMlQwUlRVSHh0YVdOeWIzTnZablF1YzJoaGNtVndiMmx1ZEM1amIyMThZaUV0ZUUxVFdrWkNjR1JyZVc5U1IwMW9iV2N4WDJoMWMwTXlja1ZSVTJwa1NXcHdhazh0WjFoVWJXOWhTSFZKV1VoRlprTjBVbG90YUV4TldXSm1hR2xvZkRBeFFrOVJOazR6U2pkRVNWUkdORWROU2xoR1NFbFBTVkJFTkRKSlFqUkdObGMlM0QlMjIlMkMlMjJpJTIyJTNBJTIyZmIxZjZhZDAtYTI2YS00ODMxLWFiYTEtYzgyNTgyYjdlYmYzJTIyJTdE)
- [x] GitHub issue related - https://github.com/Azure/azure-sdk-tools/issues/4841

- [x] We would still like to meet with Mike/Mark (together) and Arun.  However, we believe the feedback sessions will be more productive if we wait for the following: 

- UI content review + initial stakeholder UI feedback prioritized, and high priority issues addressed. There are quite a few grammar and semantic errors that have been identified. Having more folks spend time pointing out what we already know is not a good use of their time for any of us. 

- Prioritized view of GitHub issues identified through initial stakeholder feedback sessions.  So, they understand what issues have been raised and are in plan to be addressed. 
- We are ready to share Crystal’s new UI with stakeholders.  The new UI will resolve quite a few of the issues that stakeholders brought up during the feedback sessions. 
- 
### Service Partner feedback sessions 

- [x] Separate the stakeholder and service partner user studies, so we can “close out” the initial stakeholder user study and move forward with service partner review. 
- [x] Completion of UI content review, creation and prioritization of GitHub issues. The current UI has too many grammar and semantic issues. It would be best that the most noticeable issues are resolved before we introduce the app to the service partners. For example, grammar and semantic issues that are not only confusing but immediately will reduce user confidence.  
- [ ] We could start with feedback sessions for API Readiness once issues with the sign-off step are addressed.  Then schedule follow-up review for the Data Plane SDK Release app. 
- [x] There is feedback that needs to be addressed before we introduce the Data Plane SDK Release app.  For example, the integration between the Data Plane API Readiness and Data Plane SDK Release application is not good and it is confusing. Steps/actions are duplicated, arch board activities are not well defined, no way to change the PR (the PR used in Data Plane API Readiness is assumed to be the PR that will be used for SDK Release), incorrect information in the UI, and the sign-off step needs changes.  Identified and GitHub issues have been created - https://github.com/Azure/azure-sdk-tools/issues/5084.

**Comment by ladonnaq** [comment]
@ccbarragan is finishing the UX study plan and will be scheduling feedback sessions for remainder of January.

**Comment by ladonnaq** [comment]
@ccbarragan -  What is your plan for the UX study plan for service partners?  I sent the email out to the service partner on 01/24/2023.

**Comment by ladonnaq** [comment]
Closing this epic.  Crystal has completed the content review and we completed the Azure SDK stakeholder review.  Issues were created to address feedback and we have prioritized getting all feedback addressed in roadmap for Release Planner.
