### ISSUE TITLE
Release Planner V2 Stakeholder Feedback: GitHub issues that address feedback 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#5084]
## Stakeholder Feeback Sessions for Release Planner V2:  Addressing key findings

**Work in Progress:**  Will use this GitHub issue to track the GitHub issues that exist or are created to address the Release Planner V2 feedback from stakeholders. 

### User flow / process

1. Create a release plan 

- New GitHub Issues
- Existing GitHub Issues 

- [ ] [Option to show all products associated with a service · Issue #4264 · Azure/azure-sdk-tools (github.com)](https://github.com/Azure/azure-sdk-tools/issues/4264)
- [ ] [Better to indicate what's next in the banner of "Complete Your Informational Meeting first!" · Issue #4913 · Azure/azure-sdk-tools (github.com)](https://github.com/Azure/azure-sdk-tools/issues/4913)

2. API Reviews 
- New GitHub Issues
- Existing GitHub Issues 

- [ ] [When a new PR is created in the specs repo, automatically schedule a review meeting. #3916](https://github.com/Azure/azure-sdk-tools/issues/3916)
- [ ] [Need consistent way for capturing approvals as part of Service Partner Library creation process · Issue #4278 · Azure/azure-sdk-tools (github.com)](https://github.com/Azure/azure-sdk-tools/issues/4278)
- [ ] [Refine integration between other Apps and Scheduler App · Issue #4792 · Azure/azure-sdk-tools (github.com)](https://github.com/Azure/azure-sdk-tools/issues/4792)

3. API Readiness – Signoff page
- New GitHub Issues
- Existing GitHub Issues 

- [ ] [Validate API version for lifecycle milestone has met API readiness · Issue #4905 · Azure/azure-sdk-tools (github.com)](https://github.com/Azure/azure-sdk-tools/issues/4905)

3. SDK Reviews
- New GitHub Issues
- Existing GitHub Issues 

- [ ] [SDK Review Step: Cadl · Issue #4054 · Azure/azure-sdk-tools · GitHub](https://github.com/Azure/azure-sdk-tools/issues/4054)
- [ ] [API Review Step: Cadl · Issue #4053 · Azure/azure-sdk-tools · GitHub](https://github.com/Azure/azure-sdk-tools/issues/4053)
- [ ] [SDK Review - Release Planner App · Issue #4599 · Azure/azure-sdk-tools (github.com)](https://github.com/Azure/azure-sdk-tools/issues/4599)
- [ ] [Adding APIView Status Check as one of SDK ArchBoard Review Exit criteria · Issue #4692 · Azure/azure-sdk-tools (github.com)](https://github.com/Azure/azure-sdk-tools/issues/4692)
- [ ] [Gate release of client libraries on REST API merge to main · Issue #4718 · Azure/azure-sdk-tools (github.com)](https://github.com/Azure/azure-sdk-tools/issues/4718)
- [ ] [Arch Board Intro Meeting - Release Planner App and Scheduling Tool Integration · Issue #4598 · Azure/azure-sdk-tools (github.com)](https://github.com/Azure/azure-sdk-tools/issues/4598)
- [ ] [Naming Review - Azure DevEx Arch Board · Issue #4601 · Azure/azure-sdk-tools (github.com)](https://github.com/Azure/azure-sdk-tools/issues/4601)
- [ ] [Refine integration between other Apps and Scheduler App · Issue #4792 · Azure/azure-sdk-tools (github.com)](https://github.com/Azure/azure-sdk-tools/issues/4792)

4. Cadl
- New GitHub Issues
- Existing GitHub Issues 

- [ ] [Onboarding Step: Cadl · Issue #4050 · Azure/azure-sdk-tools (github.com)](https://github.com/Azure/azure-sdk-tools/issues/4050)

5. SDK Release
- New GitHub Issues
- Existing GitHub Issues 

- [ ] [Clarify quality criteria for Data Plane SDK Library release · Issue #4595 · Azure/azure-sdk-tools (github.com)](https://github.com/Azure/azure-sdk-tools/issues/4595)
- [ ] [Allow user to re-associate API Spec PR after completing API Readiness · Issue #4960 · Azure/azure-sdk-tools (github.com)](https://github.com/Azure/azure-sdk-tools/issues/4960)
- [ ] [When a service team updates the API Spec for maintenance/bug fix, ensure that a new version of the SDK is released · Issue #4768 · Azure/azure-sdk-tools (github.com)](https://github.com/Azure/azure-sdk-tools/issues/4768)
- [ ] [Multiple SDK libraries/packages of a language release upon 1 spec PR · Issue #4594 · Azure/azure-sdk-tools (github.com)](https://github.com/Azure/azure-sdk-tools/issues/4594)
- [ ] [There is no SDK auto generation for JS, Java, Python and Go in mgmt. SDK apps · Issue #5071 · Azure/azure-sdk-tools (github.com)](https://github.com/Azure/azure-sdk-tools/issues/5071)

6. End-to-end process 
- New GitHub Issues
- Existing GitHub Issues 

- [ ] [Add ability to add service team specific labels into GH issues · Issue #4109 · Azure/azure-sdk-tools (github.com)](https://github.com/Azure/azure-sdk-tools/issues/4109)
- [ ] [Link the `informational meeting` info to the API Review Meeting · Issue #3918 · Azure/azure-sdk-tools (github.com)](https://github.com/Azure/azure-sdk-tools/issues/3918)
- [ ] [When an SDK review is scheduled, include a link to all previous API reviews · Issue #3919 · Azure/azure-sdk-tools (github.com)](https://github.com/Azure/azure-sdk-tools/issues/3919)

### In-app content, terminology, and semantics 
- New GitHub Issues
- Existing GitHub Issues 

- [ ] [[PowerApps] Decide what information would be displayed after the SDK is released · Issue #4381 · Azure/azure-sdk-tools (github.com)](https://github.com/Azure/azure-sdk-tools/issues/4381)
- [ ] [Output Some Metadata in SDK Release Pipeline · Issue #4483 · Azure/azure-sdk-tools (github.com)](https://github.com/Azure/azure-sdk-tools/issues/4483)
- [ ] [Change Product presentation and behavior · Issue #4908 · Azure/azure-sdk-tools (github.com)](https://github.com/Azure/azure-sdk-tools/issues/4908)
- [ ] [Consistent naming convention across our tools... · Issue #4048 · Azure/azure-sdk-tools (github.com)](https://github.com/Azure/azure-sdk-tools/issues/4048)

### Usability and design consistency
- New GitHub Issues
- Existing GitHub Issues 

### Documentation (in app and external links)
- New GitHub Issues
- Existing GitHub Issues 

- [ ] [[PowerApps] Decide what information would be displayed after the SDK is released · Issue #4381 · Azure/azure-sdk-tools (github.com)](https://github.com/Azure/azure-sdk-tools/issues/4381)
- [ ] [De-dup SDK review process documentation · Issue #3545 · Azure/azure-sdk-tools · GitHub](https://github.com/Azure/azure-sdk-tools/issues/3545)
- [ ] [SDK Release Process Documentation update · Issue #4425 · Azure/azure-sdk-tools · GitHub](https://github.com/Azure/azure-sdk-tools/issues/4425)

**Comment by ladonnaq** [comment]
Work in process. Review all outstanding feedback against new UI to determine any remaining gaps.

**Comment by ladonnaq** [comment]
We have reviewed all of the GitHub issues and they are either addressed in current UI, new future UI, or moved to backlog for later review.
