### ISSUE TITLE
Urgent TODOs for data plane API Readiness App 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#5220]
This epic is to track the minimum todos that need to be completed before user's will be able to use the data plane API Release Readiness application.

Ready for Dev:
- [x] Update the Welcome screen to look like management plane - https://github.com/Azure/azure-sdk-tools/issues/5221
- [x] Change the text on the "Activate pull request side navigation and the screen" 
![image](https://user-images.githubusercontent.com/67656762/214688975-c3756c59-86b5-4335-86d5-b9e5e3e75171.png)
- [x] https://github.com/Azure/azure-sdk-tools/issues/5282
- [x] https://github.com/Azure/azure-sdk-tools/issues/5252
- [x] https://github.com/Azure/azure-sdk-tools/issues/5267
- [x] https://github.com/Azure/azure-sdk-tools/issues/5343
- [x] https://github.com/Azure/azure-sdk-tools/issues/5332
- [x] API Readiness validation for APEX signoff (initial signoff by API Stewardship Board) - https://github.com/Azure/azure-sdk-tools/issues/4905

Needs further discussion:
- [ ] https://github.com/Azure/azure-sdk-tools/issues/5320

Documentation work by PM:
- [ ] Update the Enable API Spec pipeline document for data plane only - https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/606/Enable-API-Spec-Pipeline - https://github.com/Azure/azure-sdk-tools/issues/5223
- [ ] Gaps in Cadl onboarding - https://github.com/Azure/azure-sdk-tools/issues/5227

**Comment by live1206** [comment]
The first two items can be handled by Dev.
The rest needs more input from PM, not ready for Dev.

**Comment by honghr** [comment]
![image](https://user-images.githubusercontent.com/88764852/215703990-d6422921-4931-41a3-9a7d-912ade60751e.png)
Change the text on the "Activate pull request side navigation and the screen" done.

**Comment by ladonnaq** [comment]
> ![image](https://user-images.githubusercontent.com/88764852/215703990-d6422921-4931-41a3-9a7d-912ade60751e.png) Change the text on the "Activate pull request side navigation and the screen" done.

- [ ] Change the button to "Associate the pull request (PR) with the current release plan". 

- [ ] Is it possible for us to determine the API version without asking the user?   It would be good to have the API version.  Can we determine the API version from the PR? If so, then after Associate the PR with Current Release Plan" is selected show the associated PR and the API version.

**Comment by honghr** [comment]
> 

1) Actually, we will activate the pull request from draft to open status, if user input pull request is draft pr. So, Do we still need remove "Activate" in the button text?
2) We cannot get API version directly. But if we must known it, we can parse the PR content to extract the API version. I don't think we must need it.

**Comment by honghr** [comment]
> > ![image](https://user-images.githubusercontent.com/88764852/215703990-d6422921-4931-41a3-9a7d-912ade60751e.png) Change the text on the "Activate pull request side navigation and the screen" done.
> 
> * [ ]  Change the button to "Associate the pull request (PR) with the current release plan".
> * [ ]  Is it possible for us to determine the API version without asking the user?   It would be good to have the API version.  Can we determine the API version from the PR? If so, then after Associate the PR with Current Release Plan" is selected show the associated PR and the API version.

1) Actually, we will activate the pull request from draft to open status, if user input pull request is draft pr. So, Do we still need remove "Activate" in the button text?
2) We cannot get API version directly. But if we must known it, we can parse the PR content to extract the API version. I don't think we must need it.

**Comment by live1206** [comment]
@honghr We will change the button text to "Associate the pull request (PR) with the current release plan" and notify the user while activating the draft PR.

**Comment by maririos** [comment]
If we are changing the verb from `Activate` to `Associate`, let's make sure to change it everywhere for consistency. For example, the menu panel on the left, the title of the page, the button, etc.
