### ISSUE TITLE
Urgent TODOs for data plane SDK Release Readiness 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#5222]
This epic is to track the minimum todos that need to be completed before user's will be able to use the data plane SDK Release Readiness application. 

- [x] Make welcome page look like management plane - https://github.com/Azure/azure-sdk-tools/issues/5221
- [x] Ensure we can get APIView approval status in the release planner app - https://github.com/Azure/azure-sdk-tools/issues/4692
- [x] https://github.com/Azure/azure-sdk-tools/issues/4595
- [ ] Enable checks to make sure SDK release requests meet release requirement- https://github.com/Azure/azure-sdk-tools/issues/5087
- [ ] The Intro Meeting vs SDK Reviews need to be earlier in the UI flow, include package name approval required for initial Beta SDK release  (Package name approval) - https://github.com/Azure/azure-sdk-tools/issues/4601 & https://github.com/Azure/azure-sdk-tools/issues/4599  & https://github.com/Azure/azure-sdk-tools/issues/4598
- [ ] SDK Release Readiness signoff (for APEX) (no actual release) - https://github.com/Azure/azure-sdk-tools/issues/5126
- [x] GA SDK Release SDK Release Readiness validation for APEX signoff 
- [x] Public Preview SDK Readiness validation for APEX signoff 
- [x] Enable user to change the PR in the SDK release planner app - https://github.com/Azure/azure-sdk-tools/issues/5157#top

**Comment by zzvswxy** [comment]
Hi @ladonnaq  for 

> GA SDK Release SDK Release Readiness validation for APEX signoff
 Public Preview SDK Readiness validation for APEX signoff

We check if SDK PR are merged and the apiview are approved in 'Sign Off DATA PLANE SDK Readiness' step.
![image](https://user-images.githubusercontent.com/20081898/216215511-f3ad278c-e24c-4656-b108-7d7b6bd3b346.png)

And we check if the SDK release pipeline are finished in 'Release DATA PLANE SDK Libraries' step.
![image](https://user-images.githubusercontent.com/20081898/216215864-de83a2af-197a-4611-be3c-54badb8e64d4.png)

Can you help me what items should we add for these two tasks?

**Comment by live1206** [comment]
> Hi @ladonnaq for
> 
> > GA SDK Release SDK Release Readiness validation for APEX signoff
> > Public Preview SDK Readiness validation for APEX signoff
> 
> We check if SDK PR are merged and the apiview are approved in 'Sign Off DATA PLANE SDK Readiness' step. ![image](https://user-images.githubusercontent.com/20081898/216215511-f3ad278c-e24c-4656-b108-7d7b6bd3b346.png)
> 
> And we check if the SDK release pipeline are finished in 'Release DATA PLANE SDK Libraries' step. ![image](https://user-images.githubusercontent.com/20081898/216215864-de83a2af-197a-4611-be3c-54badb8e64d4.png)
> 
> Is it ok for you? Can you help me what items should we check for these two tasks?

@zzvswxy  Had a discussion with @ladonnaq, the information on SDK signoff page is enough for now.
