### ISSUE TITLE
Epic: Support of additional release plane scenarios 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#5561]
I am creating this epic to track the GitHub issues associated with completion of implementation to support all additional release plan scenarios in the new UI and back-end implementation.  I will add links to GitHub issues as they are created. 

@josefree @maririos - Are there any missing use cases? 

- [ ] APEX extensions for Beta and GA product lifecycles (beta SDK releases, stable SDK release, private preview API readiness) 
- [ ] non-APEX: gaps across SDK language releases.  We could treat this as a non-APEX extension.  We have noticed that some services do not have all languages released.  For example, Cognitive has missing Java client libraries and they should be able to resolve as they move to TypeSpec + DPG.  We find similar issues in management plane. For example, the Backup services has inconsistencies in languages released across their beta and stable releases. 
- [ ] non-APEX TypeSpec + DPG 
- [ ] non-APEX: existing HLC SDKs and OpenAPI doc 
- [ ] non-APEX: existing DPG + convenience layer 
- [ ]  [ ] Management plane OpenAPI (swagger). We should modify UI across all applications to hide TypeSpec info and action items if the service is using API Spec described using OpenAPI. 
- [ ] Management plane TypeSpec.  We should modify the API readiness and SDK release apps to include any specific info or action items that relate to TypeSpec. For example, installation of Cadl, anything specific to enabling the API Spec pipeline, etc. 
- [ ] APEX new beta SDK version, new stable SDK version for management and data plane (this was there initially but is no longer implemented) 
- [ ] Maintenance release: hot fixes 
- [ ] Maintenance release: regularly SDK updates like monthly or quarterly refreshes 
- [ ] API and SDK retirement/deprecation

**Comment by maririos** [comment]
It is a good list to start with. As we have service team onboarding, we will notice which release plans we are mising

**Comment by maririos** [comment]
@ladonnaq  Looks like https://github.com/Azure/azure-sdk-tools/issues/4537 will be covered in this epic. Do you want to consolidate both into this one?

**Comment by ladonnaq** [comment]
> @ladonnaq Looks like #4537 will be covered in this epic. Do you want to consolidate both into this one?

Extensions would span multiple scenarios.  This issue is to track all of the scenarios that we need to support.  Next step would be prioritize and figure out what is needed to support.  I would expect that most of the scenarios are subset of release plan for a new initial SDK release so it should hopefully not be too difficult.

**Comment by ladonnaq** [comment]
> While this works happens, @ladonnaq has agreed to add documentation on our website on how to work around tooling limitations
I already did add guidance but if we need to duplicate it or move it let me know.  It is here now - https://eng.ms/docs/products/azure-developer-experience/onboard/requirements
