### ISSUE TITLE
UX enhancement: API readiness app

### ISSUE THREAD

**Issue by ccbarragan** [Azure/azure-sdk-tools#5566]
Review current flow and screens for API readiness app.

**Success criteria**

- Landing page shows a dashboard view of tasks in progress
- Tasks are chunked and organized logically
- Terminology is reviewed for clarity
- Design patterns meet Microsoft's accessibility guidelines

```tasklist
**Tasks**

- [ ] Review all screens in current API readiness app
- [ ] Review updates with team
- [ ] Hand-off to dev for updates in Power Apps
```

**Links**
[Link to Figma]()

**Comment by ccbarragan** [comment]
Work in progress: https://www.figma.com/file/3o7CN47eJShB8DdHFZ00cw/Azure-SDK-Release-Planner?node-id=893%3A181476&t=BHBy01l0HD9sdumo-1

**Comment by maririos** [comment]
This design overs data plane scenarios. Will it cover management plane too? orm given priorities, another GH issue/design will cover that

**Comment by ccbarragan** [comment]
> This design is for data plane scenarios. Will it cover management plane too? orm given priorities, another GH issue/design will cover that

We'll probably have to create a different issue for management plane scenarios -- will look for existing issue if it exists.

**Comment by maririos** [comment]
> > This design is for data plane scenarios. Will it cover management plane too? orm given priorities, another GH issue/design will cover that
> 
> We'll probably have to create a different issue for management plane scenarios -- will look for existing issue if it exists.

Issue https://github.com/Azure/azure-sdk-tools/issues/6654
