### ISSUE TITLE
UX enhancements: Release Planner 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#5631]
This epic will track the new UI for the release planner main application.  

```[tasklist]
### Issues that are requirements related to release planner or across Power Apps
- [x] Notification UI enhancements across all Power Apps - https://github.com/Azure/azure-sdk-tools/issues/4593
- [ ] https://github.com/Azure/azure-sdk-tools/issues/5279
- [ ] https://github.com/Azure/azure-sdk-tools/issues/5280
```

**Release Planner Design:** https://www.figma.com/file/3o7CN47eJShB8DdHFZ00cw/Azure-SDK-Release-Planner?t=20ngJ9Nlpd3LfPFk-6
**Release Planner PowerApp prototype:** https://apps.powerapps.com/play/e/ca95f761-477a-4e98-b34e-dfd5dd03a770/a/ece65a45-f966-4d8b-b04a-24329c5b8e99?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47

**Comment by maririos** [comment]
@ccbarragan I believe the design and the prototype is ready in here for Eng to start working on it. Right?

**Comment by ccbarragan** [comment]
@maririos Yes, ready for dev! All pages will need some fit-and-finish along the way (for example, the landing page / dashboard filtering interactions still need to be fleshed out). But implementation of the basic page template and structure can start at any time.

I would suggest using the [prototype in Power Apps](https://apps.powerapps.com/play/e/ca95f761-477a-4e98-b34e-dfd5dd03a770/a/ece65a45-f966-4d8b-b04a-24329c5b8e99?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47) as a jumping off point (let me know if you're unable to access).

**Comment by maririos** [comment]
@ccbarragan , @JonathanCrd was looking at the design and noticed that Figma doesn't inlude the design for the `Onboard your Product` view although it is in the prototype-ish.
Is it in another place?

**Comment by maririos** [comment]
Progress started with issues:
- https://github.com/Azure/azure-sdk-tools/issues/5671

**Comment by maririos** [comment]
Progress that we can do: 
- https://github.com/Azure/azure-sdk-tools/issues/6371

**Comment by maririos** [comment]
Before and after: https://microsoft-my.sharepoint.com/:p:/p/joncarde/EUBjDHv3pDhBuovY_ba-1EwBVwROaAsjo0cDFylyDS6_ow?e=f0mwUa
