### ISSUE TITLE
Epic for requirements for current UI and functionality Release Planner App for Data and Management plane

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#5662]
This epic is to track the requirements for the current UI and functionality of Release Planner app that needs to be done if the new UI is going to be delayed to later in Gallium or post-Gallium. 

```[tasklist]
### Tasks

- [ ] https://github.com/Azure/azure-sdk-tools/issues/5671
- [ ] https://github.com/Azure/azure-sdk-tools/issues/5699
- [ ] https://github.com/Azure/azure-sdk-tools/issues/5841
- [ ] https://github.com/Azure/azure-sdk-tools/issues/5842
- [ ] https://github.com/Azure/azure-sdk-tools/issues/5251
- [ ] https://github.com/Azure/azure-sdk-tools/issues/5233
- [ ] https://github.com/Azure/azure-sdk-tools/issues/5892
- [ ] https://github.com/Azure/azure-sdk-tools/issues/5895
- [ ] https://github.com/Azure/azure-sdk-tools/issues/5919
- [ ] https://github.com/Azure/azure-sdk-tools/issues/5922
- [ ] https://github.com/Azure/azure-sdk-tools/issues/5950
```

**Comment by maririos** [comment]
Does this include Data plane and Management plane?

**Comment by ladonnaq** [comment]
> Does this include Data plane and Management plane? We should prioritize the work for DP

Yes.

**Comment by maririos** [comment]
The work is complete :) For any new bugs or features we will move to other epic/work

**Comment by maririos** [comment]
Plus all the work done on  Plus all the issues under https://github.com/orgs/Azure/projects/318/views/48?filterQuery=area%3A%22Release+Planner%22+status%3ADone+
