### ISSUE TITLE
EPIC: Requirements data plane API readiness (current UI)

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#5695]
This epic is to track the requirements for the current UI and functionality of data plane API readiness app that needs to be done if the new UI is going to be delayed to later in Gallium or post-Gallium. 

```[tasklist]
### Tasks
- [ ] https://github.com/Azure/azure-sdk-tools/issues/5902
- [ ] https://github.com/Azure/azure-sdk-tools/issues/5504
- [ ] https://github.com/Azure/azure-sdk-tools/issues/5560
- [ ] https://github.com/Azure/azure-sdk-tools/issues/5129
- [ ] https://github.com/Azure/azure-sdk-tools/issues/5892
- [ ] https://github.com/Azure/azure-sdk-tools/issues/6122
```

Plus all the issues in: https://github.com/orgs/Azure/projects/318/views/46?filterQuery=status%3ADone+sub-area%3A%22API+Readiness%22

**Comment by maririos** [comment]
> Need to add a GitHub issue for handling API Readiness signoffs (update Azure Devops work item fields and email to APEX owners (service team and Azure SDK).

I don't see this as a necesary thing to add in the current UI. What are the implications of not developing this in the current UI?

**Comment by maririos** [comment]
> (wording around API Spec pipeline and time estimate)

API Spec pipeline work is on pause right now because of the transition work. As part of the update, we should include this

**Comment by maririos** [comment]
> API Spec pipeline work is on pause right now because of the transition work. As part of the update, we should include this

https://github.com/Azure/azure-sdk-tools/issues/5902

**Comment by maririos** [comment]
@ladonnaq could you please create an issue for 
> Need to add a GitHub issue for handling API Readiness signoffs (update Azure Devops work item fields and email to APEX owners (service team and Azure SDK)

with the respective requirements you want engineer to develop?
