### ISSUE TITLE
EPIC: Requirements as-is SDK release app (current UI)

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#5696]
This epic is to track the requirements for as-is SDK release apps (current UI). 

```[tasklist]
### Tasks
- [ ] https://github.com/Azure/azure-sdk-tools/issues/6417
- [ ] https://github.com/Azure/azure-sdk-tools/issues/6418
- [ ] https://github.com/Azure/azure-sdk-tools/issues/5069
- [ ] https://github.com/Azure/azure-sdk-tools/issues/6423
- [ ] https://github.com/Azure/azure-sdk-tools/issues/5859
- [ ] https://github.com/Azure/azure-sdk-tools/issues/6126
- [ ] https://github.com/Azure/azure-sdk-tools/issues/6068
- [ ] https://github.com/Azure/azure-sdk-tools/issues/6125
- [ ] https://github.com/Azure/azure-sdk-tools/issues/6148
- [ ] https://github.com/Azure/azure-sdk-tools/issues/6433
```

**Comment by maririos** [comment]
@ladonnaq we can repurpose this epic and have issues for both management plane and data plane as there are some that intersect. I am going to remove "Data plane" from the name

**Comment by maririos** [comment]
This is the Figma design we are going to follow for this work: https://www.figma.com/file/JzbPB3xPwrjdxJ5SiG7hYD/Design-sync%3A-SDK-readiness?type=whiteboard&node-id=0-1&t=yzB9eD8lCJ2NaGwb-0

**Comment by maririos** [comment]
SDK apps are now available in all environments and are following the Figma design
