### ISSUE TITLE
Epic for Management Plane API Readiness Requirements (need to be addressed to onboard successfully)

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#5697]
This epic is to track the requirements for the current UI and functionality of data plane API readiness app that needs to be done for management plane.  

```[tasklist]
### Tasks
- [ ] https://github.com/Azure/azure-sdk-tools/issues/4580
- [ ] https://github.com/Azure/azure-sdk-tools/issues/6124
- [ ] https://github.com/Azure/azure-sdk-tools/issues/6122
- [ ] https://github.com/Azure/azure-sdk-tools/issues/5171
- [ ] https://github.com/Azure/azure-sdk-tools/issues/5527
- [ ] https://github.com/Azure/azure-sdk-tools/issues/5902
- [ ] https://github.com/Azure/azure-sdk-tools/issues/5904
- [ ] https://github.com/Azure/azure-sdk-tools/issues/5913
- [ ] https://github.com/Azure/azure-sdk-tools/issues/5950
- [ ] https://github.com/Azure/azure-sdk-tools/issues/5857
```

Plus all the issues in: https://github.com/orgs/Azure/projects/318/views/46?filterQuery=status%3ADone+sub-area%3A%22API+Readiness%22
