### ISSUE TITLE
TypeSpec + DPG Query or Dashboard for Azure SDK team

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#5698]
TypeSpec + DPG query as interim solution until the Admin view and dashboards can be completed - https://github.com/Azure/azure-sdk-tools/issues/4045 (blocked as we need to have all release plans supported and all service teams onboarded and using the release planner before we can deliver the full dashboard experience). 

- [x] Review ADO onboard data fields, dataverse data from scheduler and release planner to determine what needs to be done to create the query.  Since ADO queries show the ADO data field name vs the label name, we may need to create a new field in order to not cause confusion. 
- [x] Create query that has all relevant fields according to the TypeSpec GitHub project - https://github.com/orgs/Azure/projects/142/views/28.  

```[tasklist]
### Tasks
- [ ] https://github.com/Azure/azure-sdk-tools/issues/5759
- [ ] https://github.com/Azure/azure-sdk-tools/issues/5870
- [ ] https://github.com/Azure/azure-sdk-tools/issues/5932
- [ ] https://github.com/Azure/azure-sdk-tools/issues/6441
- [ ] https://github.com/Azure/azure-sdk-tools/issues/6453
- [x] Implementation changes in Release Planner apps
```

**Comment by ladonnaq** [comment]
@maririos Seems only outstanding work left is the task list is this epic - https://github.com/Azure/azure-sdk-tools/issues/5759.  #5759 is focused on the integration improvements with other systems/apps and the Release Planner App.  If it is going to be a longer delay (past end of Jan 2024) in implementing the feature that enables the Release Planner App/SDK release app to create the SDK package work items, then we will need to look at re-design to represent the data in ADO in the Release Planner work item (so that way the info will be accessible in ADO query).

**Comment by maririos** [comment]
@ladonnaq If I understood your message correctly and from our conversations this week, it looks like this issue is done and we can close it.
The remaining work is more about adoption than dashboard specific, right?

**Comment by ladonnaq** [comment]
> @ladonnaq If I understood your message correctly and from our conversations this week, it looks like this issue is done and we can close it. The remaining work is more about adoption than dashboard specific, right?

We can close this work item and track closure of the adoption/improve data quality which is being tracked in this issue - https://github.com/Azure/azure-sdk-tools/issues/5759.
