### ISSUE TITLE
Validate the contents of email sent if a user onboards a service vs a product using the release planner 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#5699]
A user is no longer blocked from onboarding if there is no product that maps to the service in service tree.  At this time the onboard work item is created with the data from the Service that was found in service tree.  We need to make sure that that this scenario triggers the scheduling tool and that the email template that directs the team to schedule an Info meeting if they have not already done so.  

- [x] Review current email template that is sent for this scenario 
- [x] Confirm scheduling tool is invoked to request team to schedule an Information meeting

**Comment by JonathanCrd** [comment]
If the user selects a service that does not have an associated Product, when trying to onboard the APEX Product this warning will appear:
![image](https://user-images.githubusercontent.com/17486462/229919873-c6f2e478-6972-406b-90a9-e32fa0e287ac.png)

Now, selecting `Yes`, `Yes`, `Yes` does not trigger the schedulling tool. 
Selecting `No`, and `No` fails (uncatch error)
Selecting `Unsure` both times will actually show this message:
![image](https://user-images.githubusercontent.com/17486462/229921925-3e9c5298-3374-4475-9675-a1df61bfe2ae.png)

**Comment by JonathanCrd** [comment]
@ladonnaq do you expect the scheduler tool message to be promped on every escenario if there's no product?

**Comment by maririos** [comment]
> If the user selects a service that does not have an associated Product, when trying to onboard the APEX Product this warning will appear:

What happens when you click `Continue`? BTW there is a typo in the button. Coudl you fix it as you are already there?   https://github.com/Azure/azure-sdk-tools/issues/5233

**Comment by maririos** [comment]
> The warning gets dismissed and the user can continue onboarding the product. I even got the email with next steps.

This is the email @ladonnaq wants to look at. Could you forward it to her so she can take a look?

**Comment by maririos** [comment]
> @ladonnaq do you expect the scheduler tool message to be promped on every escenario if there's no product?

Not La Donna, but yes. If there is no Product they should always be prompt to schedule a meeting.
What I see from the original warning is that ti is covering 2 cases:

1. No product because there is no product for that service
2. No product because there is a bug on Service Tre or on our side and they should atually see a product.

For No 1 we should always prompt the scheduler
For No 2 we want them to contact La Donna.

What do you think we should do in order to cover the requirements?

**Comment by JonathanCrd** [comment]
> No product because there is no product for that service
No product because there is a bug on Service Tre or on our side and they should atually see a product.
For No 1 we should always prompt the scheduler
For No 2 we want them to contact La Donna.

We talked about this offline, for No1 I'm adding a checkbox to get explicit confirmation from the users. For No2 I don't think there is a way for us to know if something failed, however, we are providing the contact information in case their product in CLC is not showing.

**Comment by JonathanCrd** [comment]
In summary:

- The app is not asking the users to schedule an informational meeting if the service does not have a product.
  - Also, the alert window can be dismissed, so the user could skip scheduling an informational meeting.
- The warning window to let the user know that there are no products for their service is not intuitive. 
  - There is a typo that needs to be fixed.
  - The message can be redacted
  - There is not clear and explicit confirmation from the user that their product is not in CLC yet.

Another findings:
- When changing the product, the inputs won't be cleaned and the information from the previous product with ADO workitem will persist.
- When changing the Service, the old service/product information will also persist in the form.
- Going to another view and then coming back to the `Intake Questionnaire Panel` view won't restart the inputs.
- The variable `misssingProduct` is a text but it is being used as a boolean.

So, here are the individual tasks to fix the issues above:
```[tasklist]
### Tasks

- [ ] https://github.com/Azure/azure-sdk-tools/issues/5919
- [ ] https://github.com/Azure/azure-sdk-tools/issues/5233
- [ ] https://github.com/Azure/azure-sdk-tools/issues/5922
- [ ] Change `missingProduct` to a bool
```

**Comment by maririos** [comment]
Gentle ping @ladonnaq to review the email and let us know if something needs to change

**Comment by JonathanCrd** [comment]
We have gotten confirmation that the email template is as expected
