### ISSUE TITLE
Process flow for REST API Specs review with APIView

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#5760]
The purpose of this epic is to integrate APIView to the Review process of API Specs (TypeSpec, Swagger).

```[tasklist]
### Tasks
- [ ] https://github.com/Azure/azure-sdk-tools/issues/4375
- [ ] https://github.com/Azure/azure-sdk-tools/issues/4499
- [ ] https://github.com/Azure/azure-sdk-tools/issues/5375
- [ ] https://github.com/Azure/azure-sdk-tools/issues/5418
- [ ] https://github.com/Azure/azure-sdk-tools/issues/5469
```

... and more

**Comment by maririos** [comment]
I have a meeting with Mike on 8/30 to talk about this issues

**Comment by maririos** [comment]
Most of this work has been moved to the specs repo and is no longer applicable.
