### ISSUE TITLE
Increase TypeSpec and Swagger APIView usage

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#5761]
Work involved:

```[tasklist]
### Tasks
- [ ] https://github.com/Azure/azure-sdk-tools/issues/5273
- [ ] https://github.com/Azure/azure-sdk-tools/issues/5377
- [ ] https://github.com/Azure/azure-sdk-tools/issues/5521
- [ ] https://github.com/Azure/azure-sdk-tools/issues/5573
- [ ] https://github.com/Azure/azure-sdk-tools/issues/5751
- [ ] https://github.com/Azure/azure-sdk-tools/issues/5740
- [ ] https://github.com/Azure/azure-sdk-tools/issues/5833
- [ ] https://github.com/Azure/azure-sdk-tools/issues/5831
- [ ] https://github.com/Azure/azure-sdk-tools/issues/5851
- [ ] https://github.com/Azure/azure-sdk-tools/issues/5755
- [ ] https://github.com/Azure/azure-sdk-tools/issues/5941
- [ ] https://github.com/Azure/azure-sdk-tools/issues/5955
- [ ] https://github.com/Azure/azure-sdk-tools/issues/6174
- [ ] https://github.com/Azure/azure-sdk-tools/issues/6108
- [ ] https://github.com/Azure/azure-sdk-tools/issues/6295
```

**Comment by heaths** [comment]
@maririos @mikekistler should we add some of the various diff'ing problems we've seen here as well, or is that redundant? If the diff'ing doesn't work adequately, doing subsequent REST API reviews via APIView is not practical. #6296 comes to mind.
