### ISSUE TITLE
Onboard service teams to use existing release planner for subset of APEX scenarios 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#5828]
- All service teams should begin using the release planner to track and validate API readiness for Private Preview, Public Preview, and GA.  Data plane (TypeSpec + DPG supported). 
- All service teams should begin using the release planner to track API readiness and SDK release readiness for Private Preview, Public Preview and GA for management plane. (TypeSpec and OpenAPI supported). 

### Requirements

- [ ] https://github.com/Azure/azure-sdk-tools/issues/5662
- [ ] Update the private preview API readiness launch criteria to instruct service teams to use the release planner for validation that launch criteria is completed for APEX signoff 
- [ ] Update management plane Public Preview and GA launch criteria to instruct service teams to use the release plane to validate API readiness and SDK release readiness for APEX signoff vs using the survey/form 
- [ ] Communication to management plane service teams inviting them to use the release planner to validate requirements for their upcoming launches 
- [ ] Meet with service teams in scope for TypeSpec + DPG SDKs to begin having them use release planner for API readiness with current UI.

**Comment by maririos** [comment]
@ladonnaq as you are currently working on this, I have moved the epic `Status: In Progres`

**Comment by maririos** [comment]
I moved the Release of thi Epic to July as the Release planner and the API Readiness app are ready for service teams to consume

**Comment by maririos** [comment]
@ladonnaq I think this issue is done, right?

**Comment by maririos** [comment]
Missing work here:
- Updates on docs in Eng Hub
- https://github.com/Azure/azure-sdk-tools/issues/6253
