### ISSUE TITLE
Create doc templates + align on basic structure

### ISSUE THREAD

**Issue by ccbarragan** [Azure/azure-sdk-tools#6083]
Follows https://github.com/Azure/azure-sdk-tools/issues/5989. Test out different structures to best accommodate incoming service partner docs.

#### Success criteria

- Organization of content focuses on service partner success while carefully considering contributions and helping to reduce friction for our internal team
- Basic structure is approved by stakeholders
- Doc templates are created to bring consistency to incoming content

#### Tasks

- [x] Kick off v-team meeting with stakeholders to brainstorm primary jobs-to-be-done
- [x] Try out different structures and work with @konrad-jamrozik @maririos for quick check
- [x] Lock in structure and get general templates created

#### Links

https://eng.ms/docs/products/azure-developer-experience/

**Comment by ccbarragan** [comment]
Kick-off complete 🎉 Link to Figjam board: https://www.figma.com/file/EB1QVuB46apU3zj9djvy3C/V-team-brainstorm%3A-Azure-SDK-service-partner-docs?type=whiteboard&node-id=0%3A1&t=irmFdJnp88Yz5gUy-1

Structure updates currently in progress.

**Comment by ccbarragan** [comment]
Docs are now open for v-team contributions! Updated the [readme](https://dev.azure.com/azure-sdk/internal/_git/azure-sdk-docs-eng.ms) and added [basic templates](https://dev.azure.com/azure-sdk/internal/_git/azure-sdk-docs-eng.ms) for getting started. Closing.
