### ISSUE TITLE
Namespace Approval for Management Plane: Move the "Review Ticket" box from management plane API readiness to SDK release app

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#6125]
Before initial beta SDKs (management libraries) are released, the arch board must approve the namespace for the language packages.  
There is a field in the API readiness app for user's to input the GitHub issue that is being used to track the namespace approvals.  This action/step is part of SDK release not API readiness.   

```[tasklist]
### Tasks
- [x] Remove the "Review Ticket" field from the API readiness milestone (Power App)
- [ ] Add the "Review Ticket" box to the SDK Release milestone and change the name to "Namespace Approval GitHub Issue".  We have discussed a new screen to remind teams they need to complete the namespace approvals for initial beta release. 
- [ ] This field only shows up for new initial beta SDKs and the Public Preview release plan.  The ADO Field Mgmt library release type will be "new initial version (not updating existing SDKs)".  Right now we are manually selecting this field but the release planner should set this field when there is a release plan for "new SDK version".  Right now the only release plan available is "New initial beta".  See this GitHub issue - https://github.com/Azure/azure-sdk-tools/issues/5701

```

**Comment by maririos** [comment]
@ladonnaq 
Shoudl the explanation of the process to ask for namespace review should be in an independent view? or as part of a view?

**Comment by maririos** [comment]
Changes based on design https://www.figma.com/file/JzbPB3xPwrjdxJ5SiG7hYD/Design-sync%3A-SDK-readiness?type=whiteboard&node-id=0-1&t=1lCBRP1NpVo69ZVV-0
