### ISSUE TITLE
Onboard non-APEX service partners to create release plans for management and data plane 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#6264]
This requirement is for changes needed to onboard service teams who are working on non-APEX data plane migration to TypeSpec + DPG.  

```[tasklist]
### Tasks
- [ ] https://github.com/Azure/azure-sdk-tools/issues/5932
- [ ] https://github.com/Azure/azure-sdk-tools/issues/6262
- [ ] https://github.com/Azure/azure-sdk-tools/issues/5701
- [ ] https://github.com/Azure/azure-sdk-tools/issues/7314

```

**Comment by maririos** [comment]
Closing as all issues are done. 
For https://github.com/Azure/azure-sdk-tools/issues/7314 it will be covered in #8947
