### ISSUE TITLE
Data Plane SDK Release Readiness Signoff Screen 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#6403]
This issue will be used to track requirements for changes to the SDK Release Readiness signoff screen/blade in the SDK release app for data plane (TypeSpec + DPG). 

```[tasklist]
### Tasks
- [ ] Change name to SDK release readiness 
- [ ] Only show the screen if the release plan is in scope for APEX 
- [ ] Ensure the PR is in the public repo (backend check).  If not in the public repo, then include information on how to publish the API Spec to the public repo or include link to the OpenAPI Hub feature that will complete this task for the user.  
- [ ] If **new beta (new initial),** then namespace approval is needed for management plane and data plane before initial beta SDKs are released. 
- [ ] If **new stable (new initial)**, then arch board APIView needs to be approved for each language for data plane.  Also, testing and samples need to be on target for stable SDK release. For management plane, .NET SDK must have SDK review with Arch Board and .NET SDK architects must signoff for .NET stable release.  This must be done before the initial release of the other languages.  Also, .NET samples and testing should be completed for stable SDK release. 
- [ ] Option to "Submit for APEX validation" if the release plan is in scope for APEX.  If all criteria is met then the Submit for APEX validation button/option is enabled.  Once submitted, email should be sent to APEX PM and Azure SDK Engagement PMs (azsdkapex@microsoft.com).  I will draft email in word and provide link by end of day on 06/28/2023. 
```

**Comment by ladonnaq** [comment]
This item will be closed.  We will use this GitHub issue to track changes to data plane SDK release signoff screen for current UI.  https://github.com/Azure/azure-sdk-tools/issues/6417
