### ISSUE TITLE
Data Plane SDK Release App - update UI flow so that it is same as the DPG wiki page 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#6433]
The SDK release app does not have all of the steps and information that is described in the DPG wiki page.   We need to step through the wiki page and app to make sure that we have all of the required steps and information for user in the app.  Link to DPG wiki page - https://aka.ms/azsdk/dpcodegen. 

```[tasklist]
### Tasks
- [x] Walk-thru the DPG wiki page and compare to the SDK Release app to identify gaps.
- [x] Determine which gaps we will resolve now and what will wait for the new UI.
- [x] Are there any gaps in tooling or automation?  If so, document and put in backlog for discussion for future roadmap (new UI and beyond)
- [x] There is no link to the release checklist, which has a great deal of requirements that are needed for SDK release.  Also, it is not clear from looking at the release checklist if a service partner has to do EVERY step and what steps are absolutely required for beta release vs stable release.  Any difference between initial beta or stable release vs new beta or stable version.
- [x] We need to include permissions info/checks in the SDK release app b/c it is different permissions needed to release SDKs.
```

**Comment by maririos** [comment]
@ladonnaq is this something you could help identify so we get more clear requirements?

**Comment by maririos** [comment]
This has been covered by the Figma design: https://www.figma.com/file/JzbPB3xPwrjdxJ5SiG7hYD/Design-sync%3A-SDK-readiness?type=whiteboard&node-id=0-1&t=yzB9eD8lCJ2NaGwb-0
