### ISSUE TITLE
Integrate work item from dashboard into the Release Planner apps

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#6453]
This issue will track the work that is needed in order to connect all the Release Planner apps with the specific ADO workitems that compose the Azure SDK dashboard.

Design is here: https://github.com/Azure/azure-sdk-tools/issues/5932

```[tasklist]
### Tasks
- [ ] https://github.com/Azure/azure-sdk-tools/issues/6477
- [ ] https://github.com/Azure/azure-sdk-tools/issues/6475
- [ ] https://github.com/Azure/azure-sdk-tools/issues/6478
- [ ] https://github.com/Azure/azure-sdk-tools/issues/6370
```

**Comment by maririos** [comment]
Initial meeting has been schedule with Eng team to look into this work

**Comment by maririos** [comment]
Eng are looking into the custom query and understanding relationships and data aggregated here.
Action items we need to assign and work on:
- Design in dataverse for this data
- Design how data will keep in sync between Dataverse and the ADO work items
- Implementation design on how to work with existing work items (onboarding) and new work item types
- Document which work item will be created at which step of the Release Plan process
  - Include specific fields

**Comment by maririos** [comment]
After looking more into it, decision was to move issue https://github.com/Azure/azure-sdk-tools/issues/6476 to backlog as it is not a priority for now
