### ISSUE TITLE
APIView comments database

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#6460]
Issue to track the work that might come to APIView as we look into adding ChatGPT to it

```[tasklist]
### Tasks
- [ ] https://github.com/Azure/azure-sdk-tools/issues/6647
- [ ] https://github.com/Azure/azure-sdk-tools/issues/6648
- [ ] https://github.com/Azure/azure-sdk-tools/issues/6649
- [ ] https://github.com/Azure/azure-sdk-tools/issues/6650
```
