### ISSUE TITLE
UX design pattern: Horizontal step wizard

### ISSUE THREAD

**Issue by ccbarragan** [Azure/azure-sdk-tools#6629]
Draft UX design pattern around horizontal step wizards for Release Planner + associated apps. 

Previous guidance: [Horizontal tab list](https://www.figma.com/file/3o7CN47eJShB8DdHFZ00cw/Azure-SDK-Release-Planner?type=design&node-id=769%3A167258&mode=design&t=Snu9yPkyBNrxWsX2-1), [Step wizard](https://www.figma.com/file/3o7CN47eJShB8DdHFZ00cw/Azure-SDK-Release-Planner?type=design&node-id=769%3A168302&mode=design&t=Snu9yPkyBNrxWsX2-1)

**Success criteria**
- Design pattern is scalable and can be applied across other apps to create a coherent experience for service partners.
- Design pattern is pressure-tested for accessibility, color, and usability.
- Design pattern reuses common Fluent components.

**Tasks**

- [x] Create lo-fi designs for review
- [ ] Add to templated pattern guidance
- [ ] Hand-off for implementation

**Comment by ccbarragan** [comment]
Lo-fi concepts: https://www.figma.com/file/JzbPB3xPwrjdxJ5SiG7hYD/Design-sync%3A-SDK-readiness?type=whiteboard&node-id=303%3A13901&t=iz2ZGiDEft8DIXgE-1

**Comment by ccbarragan** [comment]
Fluent 2 doesn't have a designated step wizard component. Instead, developers modify the [Tablist](https://fluent2.microsoft.design/components/web/react/tablist/usage) component.

Other examples of step wizards:

- Azure: https://eng.ms/docs/products/azure-portal-framework-ibizafx/designguide/templates/design-patterns-step-wizard
- Coherence: https://coherence-portal.azurewebsites.net/Controls/Wizard#Examples&Product%20sample
