### ISSUE TITLE
**GAP** Users having difficulty finding API readiness milestone

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#6640]
I have had feedback from several service teams that they did not know where to find the API readiness milestone.  

What can we do to help? 

- [ ] Update docs to be more specific with screenshots.  I know that screenshots are not desired in docs but teams are having difficulty navigating the current UI implementation in the Release Planner App and associated apps. 
- [ ] Implement the Release Planner dashboard that Crystal provided preliminary designs for in Figma - https://www.figma.com/file/3o7CN47eJShB8DdHFZ00cw/Azure-SDK-Release-Planner?type=design&node-id=110-1268&mode=design&t=iNlEyeTqoRsC548F-0

**Comment by maririos** [comment]
Not sure I understand. They can't find their Release Plan and therefore they can't find the API Readiness milestone?

**Comment by ladonnaq** [comment]
@maririos - They seem to be having difficulty navigating the Release Planner.  For some reason, we are having to explain they need to click on the milestone menu option to the left.  Maybe we could have a link to the milestone from the progress section of the screen.  That way they can access the milestone from the progress section or the milestone tab in the menu. 



![Image](https://github.com/Azure/azure-sdk-tools/assets/67656762/3c79f2a2-088b-4432-a0ae-1aa04dc4ce25)

**Comment by maririos** [comment]
Ohhh yes! I see that. 
Thank you for explaining. We also got that feedback https://github.com/Azure/azure-sdk-tools/issues/6791

We can definitely do this :)

**Comment by maririos** [comment]
- [ ] Data plane API readiness
- [ ] Management plane API readiness

**Comment by JonathanCrd** [comment]
Progress bars are now clickable, and I added a button to make it more explicit.



![Image](https://github.com/Azure/azure-sdk-tools/assets/17486462/10fa725f-f6a5-47e8-96fd-1d2f25f02007)
