### ISSUE TITLE
[APIView] APIView Reviews / Revisions / Comments Structure

### ISSUE THREAD

**Issue by chidozieononiwu** [Azure/azure-sdk-tools#6746]
### **Problem Summary**

- There are multiple independent reviews with the same package name that don't share history (Comments and Revisions) and cannot be diffed across revisions resulting in the following difficulties.
         - Difficulty identifying which review/revision to work with
         - Difficulty finding old review/ revisions that have been previously interacted with (approved, reviewed, commented on)
         - Difficulty viewing comment from related review / revisions
         - No ability to diff across related review/ revisions

### **Proposed Solution**
-  Restructure APIView to group all revisions regardless of the type under one Review for one package / language.
e.g. Azure.Template for C# should have one Review with all C# template revisions grouped under it.
and @azure/template for JavaScript should have one Review with all JS template revisions under it

### **Proposed Plan**

- [x] Create a clone of the Database and restructure 'schema' to support proposed plan.
- [x] Update App logic to run off clone of database (Estimated Completion: Friday 3rd November 2023)
- [x] Update Pipeline Automation to call updated API (Estimated Completion: Friday 10th November 2023)
- [x] Estimated deployment to prod is Nov 27th

**Comment by maririos** [comment]
Deployed on 12/8
