### ISSUE TITLE
EPIC: Scenario Testing for Data Aggregation Model for Engagement Experience

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#6909]
We will use this epic to track the bugs, requirements, etc that are found during the scenario testing.  

**Scenario Testing and test case information:**  

- [Test cases and results](https://microsoft-my.sharepoint.com/:x:/p/v-yoganandak/EQFLL66ahVtNrTH8e3lhqJUBndOrpHxkG1qp10FA5ynR1g?e=htuFmC)
- [Scenarios](https://microsoft-my.sharepoint.com/:w:/p/ladonnaquinn/EUGCLowSkvtEsTB8G8WJj-UB8tYins06CSwMWCYkxUC8NQ?e=aGb436)

```[tasklist]
### Tasks
- [ ] https://github.com/Azure/azure-sdk-tools/issues/6912
- [ ] https://github.com/Azure/azure-sdk-tools/issues/6908
- [ ] https://github.com/Azure/azure-sdk-tools/issues/6911
- [ ] https://github.com/Azure/azure-sdk-tools/issues/6902
- [ ] https://github.com/Azure/azure-sdk-tools/issues/6901
```

**Comment by maririos** [comment]
New testing has confirmed this is done
