### ISSUE TITLE
Create Private Preview Release Plan - missing data in work items 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#7025]
Scenario: Create a Private Preview Release Plan for Management Plane and Data Plane 

Spreadsheet: https://microsoft-my.sharepoint.com/:x:/p/ladonnaquinn/ETD9YCt4cfxHlL4mC1KlVygBIQss1mm6NMIpu3_BdOJhJQ?e=HWMD10

```[tasklist]
### Tasks
- [ ] Epic Product Type:  PrivPrev Release Plan Submitted Date, Mgmt PrivPrev API Spec PR, Mgmt PrivPrev Release Plan, Mgmt PrivPrev Release Plan State, Data PrivPrev API Spec PR link, Data PrivPrev Release Plan State, Data PrivPrev Release Plan link
- [ ] Epic Product Type:  Gap - missing field for PrivPrev Release Plan Submitted Date for data plane, only have field for management plane.  (I can create the field but we need to coordinate so nothing breaks). 
- [ ] Epic Product Type: State change should be the same as the product lifecycle in Service Tree.  The Product Lifecycle is the current lifecycle of the product. APEX target lifecycle is the next lifecycle, the one they are actively working to complete.  Ideally there should be a scheduled job that runs and updates any changes from data that is in service tree.  This field should be updated as part of that job that runs.  
- [ ] Triage work item:  Change state to Completed.  
- [ ] Release Plan work item: Product Service Tree Link is missing data.  
- [ ] Spreadsheet with data mapping - https://microsoft-my.sharepoint.com/:x:/p/ladonnaquinn/Ea9NsvoCyaVAjqnfexY7wsQBrlONi9WtSmWNk_l4r-0sfg?e=Csc6zA.  Look at Create-PrivPrev-Data and Create-PrivPrev-Mgmt tabs.  This will have all work items type that need updated, fields to update, where data is located or how to calculate if needed, etc.  We can use the spreadsheet to ensure all is complete and to address any questions about implementation.  
```

**Comment by maririos** [comment]
>  Epic Product Type: Gap - missing field for PrivPrev Release Plan Submitted Date for data plane, only have field for management plane. (I can create the field but we need to coordinate so nothing breaks).

@ladonnaq  creating fields doesn't break automation. Removing fields or changing picklist values do break automation

**Comment by maririos** [comment]
@ladonnaq is this still accurate? or have other issues taken precedent of this

**Comment by ladonnaq** [comment]
All work is done except for data automation for "completing" release plan.  I will create a new issue for tracking all together (vs by release plan type).
