### ISSUE TITLE
Create a public preview release plan - missing or gaps in data 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#7026]
Scenario: Create a release plan for public preview for management and data plane 

```[tasklist]
### Tasks
- [ ] Epic product type:  None of the fields expected are being updated.  I will create new spreadsheet that will also include the updates that are expected after the SDK release app is deployed so that we can make sure that everything is completed.
- [x] Epic service type: State should change when service lifecycle changes in service tree.  This should be part of a regularly scheduled job that runs to sync data from service tree.
- [ ] Release Plan work item: Data plane SDK release type, Mgmt library release type, Product Service Tree Link, State should be updated to Not Started until activity begins on the release plan.
- [ ] Package work items:  Info will be in spreadsheet because this has not been implemented yet.
- [ ] TODO La Donna:  Create new spreadsheet.  Target to complete by no later than Friday 09/28/2023.
```

**Comment by maririos** [comment]
No longer applicable
