### ISSUE TITLE
Create a release plan GA - missing or gaps in data 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#7027]
Scenario:  Create a GA release plan for management plane and data plane 

Spreadsheet:  https://microsoft-my.sharepoint.com/:x:/p/ladonnaquinn/ETD9YCt4cfxHlL4mC1KlVygBIQss1mm6NMIpu3_BdOJhJQ?e=HWMD10

```[tasklist]
### Tasks
- [ ] Epic product type:  None of the fields expected are being updated.  I will create new spreadsheet that will also include the updates that are expected after the SDK release app is deployed so that we can make sure that everything is completed.  
- [ ] Epic service type: State should change when service lifecycle changes in service tree.  This should be part of a regularly scheduled job that runs to sync data from service tree. 
- [ ] Release Plan work item: Data plane SDK release type, Mgmt library release type, Product Service Tree Link, State should be updated to Not Started until activity begins on the release plan. 
- [ ] Package work items:  Info will be in spreadsheet because this has not been implemented yet. 
- [ ] TODO La Donna:  Create new spreadsheet.  Target to complete by no later than Friday 09/28/2023. 
```

**Comment by maririos** [comment]
@ladonnaq is this still accurate? or have other issues taken precedent of this

**Comment by ladonnaq** [comment]
All work is completed but the data automation for "completing" a release plan.   I will create a new issue to track these together for all release plans types.
