### ISSUE TITLE
Onboard - Data fields need to be included in automation for Epic Service 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#7059]
During onboarding the following fields need to be updated for Epic type Service.  https://microsoft-my.sharepoint.com/:x:/p/ladonnaquinn/ETD9YCt4cfxHlL4mC1KlVygBIQss1mm6NMIpu3_BdOJhJQ?e=AdgtT0&nav=MTVfezA3NUY0OTI4LUVBRkYtNEQwNS04Mjk0LTFCQzg5ODgxOTk1Rn0

See spreadsheet onboard data missing tab-

- [ ] State Field needs to be updated when onboarding and regularly synced so that the state always matches what is in service tree.  
- [ ] Service Onboard Date Field in the epic service needs to be updated when onboarded the first time and this field value does not change.  This is to make it easier for us to provide requested metrics (i.e. how many new services are coming in over time?, etc). 
- [ ] isServiceNew Field should be updated during onboarding.  This field will also need to be updated after GA API readiness is completed and the stable API version is merged.  At this time, the SDK team will consider it an existing service as the target for TypeSpec migration is no stable API is published yet.  
- [ ] All existing epic-product and epic-service need to have the state changed.  I have manually updated based on the state of the onboard work items and lifecycle fields for service and product in the work item.  This is out of sync though with service tree.  We need to correct this because it is important to understanding new services vs existing services and tracking teams that need to migrate to TypeSpec.

**Comment by ladonnaq** [comment]
This a duplicate of https://github.com/Azure/azure-sdk-tools/issues/7082 so closing.
