### ISSUE TITLE
Epic Product Field Updates - Onboard a new or update triage for a product 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#7080]
Link to spreadsheet tab for details-sort by Epic Product - https://microsoft-my.sharepoint.com/:x:/p/ladonnaquinn/Ea9NsvoCyaVAjqnfexY7wsQBrlONi9WtSmWNk_l4r-0sfg?e=BIZthT&nav=MTVfezA3NUY0OTI4LUVBRkYtNEQwNS04Mjk0LTFCQzg5ODgxOTk1Rn0

- [x] CLC Link Field - no data, this field should be updated when onboarding initially or if a service team is onboarding again to update triage information.  
- [x] State - This field should be initially set during onboarding and need to continually keep in sync with Service Tree.  The field should represent the **_current lifecycle_** of the product, not the **_target lifecycle_**.  
- [x] Product Onboard Date (New Field to be added to the epic template to track date of onboard).  This field value does not change after initial onboarding.  This date is to ensure we can get metrics like "number of products onboarding over time".  
- [x] ReleasedSDKs - This value should be updated after a Public Preview or GA release plan is completed.  For Public Preview, the value should be initial Beta SDKs released for <list languages> and for GA should be initial Stable SDKs released for <list languages>.  Field is blank until the initial Beta SDKs are released.

**Comment by maririos** [comment]
@ladonnaq for clarifying questions:

> CLC Link Field - no data, this field should be updated when onboarding initially or if a service team is onboarding again to update triage information.

How is the information in field `Product Service Tree Link` different than the information in `CLC link`?

> State - This field should be initially set during onboarding and need to continually keep in sync with Service Tree. The field should represent the current lifecycle of the product, not the target lifecycle.

You mean the state the product has in Service Tree?

> Product Onboard Date (New Field to be added to the epic template to track date of onboard).

Could you add it to the template? Also do you want this field to be updated if the user onboards this product again?

**Comment by maririos** [comment]
More questions for `ReleasedSDKs`: 
- Could you explain more the purpose of this field?
- Current field type is Text. It would be better to have a picklist so there are no gramatical errors
- Why adding the list of languages is important? why not look at the associated package workitems?
- Update when Public preview is completed to `initial Beta SDKs`. What happens if the user creates a second release plan targeting Public preview (for a small update) and then they release another beta SDKs, at this point those SDKs are not `initial Beta`, they could be `beta.2` ... no? or what is the point of `initial Beta`?
- Update when GA release plan is completed to 'Initial Stable SDKs`. Same question as scenario above.

**Comment by ladonnaq** [comment]
> @ladonnaq for clarifying questions:
> 
> > CLC Link Field - no data, this field should be updated when onboarding initially or if a service team is onboarding again to update triage information.
> 
> How is the information in field `Product Service Tree Link` different than the information in `CLC link`?
> 
> > State - This field should be initially set during onboarding and need to continually keep in sync with Service Tree. The field should represent the current lifecycle of the product, not the target lifecycle.
> 
> You mean the state the product has in Service Tree?
> 
> > Product Onboard Date (New Field to be added to the epic template to track date of onboard).
> 
> Could you add it to the template? Also do you want this field to be updated if the user onboards this product again?

1.  **CLC Link Field** is not the service tree link.  It is the Cloud LIfecycle Link to the APEX signoff record in Cloud LIfecycle app (which is a S360 app).  This link was in the old onboard work item so I know that it was being created before.  Here is a link to CLC record for Dev Box - https://vnext.s360.msftcloudes.com/cloudLifecycle/products?peopleBasedNodes=&global=8:2f8ac231-74e7-4980-83c4-16dfc1e725a3&blade=stage:3~program:All~kpiowner:All~Domains:All~_loc:cloudLifecycle&actionItemId=
2. State of a product should match the "Current Lifecycle" state as found in service tree metadata.  This information does need to be always synced with the metadata in service tree so that our data is accurate.  Right now it is very tedious and time consuming to make sure these are in sync.  I manually updated all of the states of the epics for products based off the last time that Siva manually updated them (which was in June) so they are out of sync now.  I need this information b/c it is the most accurate way to flag new products so we can investigate their current status on TypeSpec adoption. This is especially important for data plane because the service may be GA but there is a new "product" which requires new initial data plane REST APIs and beta SDK packages. This happens frequently for Cognitive, Azure Communications, etc.  Here is an example.  Here is the service tree link for Azure Content Moderator (the associated service) for Azure AI Content Security -https://microsoftservicetree.com/services/26e0af03-ed36-428f-988a-e538b5f726c0. The service current lifecycle stage is GA as of 04/19/2017(look at metadata in lifecycle).  Azure AI Content Security required new initial data plane REST APIs and new initial beta SDKs.  Azure AI Content Security product's current lifecycle is currently Public Preview (and they onboarded with us during Private Preview). If were to just look at the service state, then the scoping for TypeSpec would be inaccurate.  So I need the states for product and service so that we can ensure we are engaging all teams that need to adopt TypeSpec.  
3.  Product Onboard Date - Field is Epic product onboard date and label is onboard date.  This field should only be updated during initial onboarding as we want to track products onboarding over time so we need a "timestamp".

**Comment by ladonnaq** [comment]
> * How is the information in field `Product Service Tree Link` different than the information in `CLC link`?
> * We should have a `isProductNew` field too because of the TypeSpec effort. They want both service and product that is new.
> 
> More questions for `ReleasedSDKs`:
> 
> * Could you explain more the purpose of this field?  **I want a way to track if beta or stable SDKs have been released for the product.  This is another field we can use to help identify products that we can engage to adopt TypeSpec.  If the have only beta SDKs released, then we can add them to our queue of teams to discuss onboarding to adopt TypeSpec.**  
> * Current field type is Text. It would be better to have a picklist so there are no gramatical errors.  **Good point I was trying to use fields we had there already.  I can create a new field that is a picklist with beta SDKs, stable SDKs, no SDKs.  That should make it clear so we can use it as field to scope for TypeSpec.** 
> * Why adding the list of languages is important? why not look at the associated package workitems?  **You are correct we don't need to indicate the languages. If they have any, even one stable SDKs, then we would lower the priority for discussing TypeSpec.**  
> * When onboarding, value should be blank, right?  **That is correct unless they have indicated they have previously released SDKs.  I am not sure if there as way to programmatically figure that out unless they choose a SDK package from the dropdown list (which is not working well and we had agreed to remove it for now until we have time to improve the UI).  So perhaps for now this field will be manually updated during onboarding and then programmatically after the teams complete release plans (we ask if they are releasing beta or stable in the release plan UI flow so we should have the data and the released package info to update the field accordingly).**  
> * Update when Public preview is completed to `initial Beta SDKs`. What happens if the user creates a second release plan targeting Public preview (for a small update) and then they release another beta SDKs, at this point those SDKs are not `initial Beta`, they could be `beta.2` ... no? or what is the point of `initial Beta`?  **Good point as right now we can't distinguish between exception release plans and release plan for APEX lifecycle milestones in the Release Planner App.  Right now, we are manually selecting the release plan type for extensions.  This is what the fields are now in ADO for release plan type. 
![image](https://github.com/Azure/azure-sdk-tools/assets/67656762/4558b631-ca1e-4b57-adc0-58057a55ef5a) 

Suggested logic: 

- If ReleasedSDKs field is No SDKs, and the release plan is Public Preview or GA, then update the field according to the SDKs that were released (Beta SDKs or Stable SDKs). 
- If ReleasedSDKs field is Beta SDKs and the release plan is Public Preview or GA, and Stable SDKs were released update the field to Stable SDKs. 
- If ReleasedSDKs field is Stable SDKs, then no updates needed.** 

> * Update when GA release plan is completed to 'Initial Stable SDKs`. Same question as scenario above.  **See response above.**

**Comment by maririos** [comment]
Conclusion for Eng team:

- CLC link (we had it in onboarding work item so we might have the logic for it…)
- State field should be the value for product current lifecycle stage in service Tree
- isProductNew: TBD
- Onboard date: add value when product work item doesn't exist
- Released SDKs type field: 
  - When onboarding leave blank
  - Update only when the field value is different than `stable SDKs`. If the value is different, then when a release plan is completed update the value with the SDK type that was released.
