### ISSUE TITLE
Epic Service Fields - Onboard a new or update triage for product 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#7082]
Link to spreadsheet with details, look in the Onboard-dataMissing tab - https://microsoft-my.sharepoint.com/:x:/p/ladonnaquinn/ETD9YCt4cfxHlL4mC1KlVygBIQss1mm6NMIpu3_BdOJhJQ?e=6VqO7v 

- [x] State Field needs to be updated when onboarding and regularly synced so that the state always matches what is in service tree.  The state should be the current lifecycle stage not the target lifecycle stage.  The target is next which is what the team is working on right now for the next lifecycle milestone. For example, teams working on the target lifecycle of Private Preview, have a current lifecycle of In Dev. 
- [x] Service Onboard Date Field in the epic service needs to be updated when onboarded the first time and this field value does not change. This is to make it easier for us to provide requested metrics (i.e. how many new services are coming in over time?, etc).
- [x] isServiceNew Field should be updated during onboarding. This field will also need to be updated after GA API readiness is completed and the stable API version is merged. At this time, the SDK team will consider it an existing service as the target for TypeSpec migration is no stable API is published yet.
- [x] All existing epic-service type need to have the state changed. I have manually updated based on the state of the onboard work items and lifecycle fields for service and product in the work item. This is out of sync though with service tree. We need to correct this because it is important to understanding new services vs existing services and tracking teams that need to migrate to TypeSpec.

**Comment by maririos** [comment]
> This field should be synched on a regular basis so that our information is current with what is in service tree. 

Do you mean that there should be a back-end process that is constantly updating this information for a Service/Product ?
What should be the frequency? 

>  Service Onboard Date (New Field) - If the epic type service is found during onboarding, then skip adding a date to this field. If no epic service exist, then the date of onboarding is the date to use for service onboard date.

Only add this date if the automation creates the Service and/or Product work item. Don't modify when the service/Product onboards again ?

**Comment by maririos** [comment]
> Service Onboard Date Field 

Field added in the Epic template

**Comment by maririos** [comment]
More questions:
- `Onboard date`: should the value only be added if the Release planner created the Service epic? or should the value be added if the `Onboard date` field is empty? (the later will cover cases where the service already has a record with us, but they recently onboarded with us.
-  `isServiceNew` : should this be updated when any of the products inside the service reached GA for API readiness? or only when all products?

**Comment by ladonnaq** [comment]
> **Update**: These questions have been answered and are included as part of the description of the issue
> 
> @ladonnaq
> 
> > This field should be synched on a regular basis so that our information is current with what is in service tree.
> 
> Do you mean that there should be a back-end process that is constantly updating this information for a Service/Product ? What should be the frequency?  **There are data values that are populated by the release planner during onboarding that are critical to the accuracy of our data, especially in identifying, engaging, and tracking service teams that need to adopt TypeSpec. 
I have created a tab in the spreadsheet for this data - https://microsoft-my.sharepoint.com/:x:/p/ladonnaquinn/ETD9YCt4cfxHlL4mC1KlVygBIQss1mm6NMIpu3_BdOJhJQ?e=AkLeMo&nav=MTVfe0ExRjNGN0Y5LTY0NjItNEMwRS1CRjM3LTI1QTcwRjhCNkY0Q30.  I will create a GitHub issue and link to the tab so that there is clarity into all of the fields that must be synced on a regular scheduled basis.  Right now I have some onboarding data values in the tab that I need to remove. Also, some fields that are duplicated which I want to eliminate (so that only updating field in the work item that represents the official record on our side). Once I do that, will open the GitHub issue.  Since this data can change at any time, it would be good to run a scheduled job that updates daily at minimum.**  
> 
> > Service Onboard Date (New Field) - If the epic type service is found during onboarding, then skip adding a date to this field. If no epic service exist, then the date of onboarding is the date to use for service onboard date.  **That is correct.  As I mentioned in another issue. I am sorting out to manually get this date and update it for all of the existing services.**  
> 
> Only add this date if the automation creates the Service and/or Product work item. Don't modify when the service/Product onboards again ?  **That is correct. The onboard date fields are a "time stamp" so we can provide the metrics we are continually being asked to provide in regards to "how many product and/or services are we onboarding in a specific time period".  Previously we were using the onboard creation date but that only is the product onboard date.  The service may have other products that have GA'd so we can't rely on the product onboard date to be the same as the service onboard date.**

**Comment by maririos** [comment]
Conclusion for Eng team:

- State field should be the value for service current lifecycle stage in service Tree
- Onboard date: add value when service work item doesn't exist
- isServiceNew: TBD

**Comment by maririos** [comment]
@praveenkuttappan issue updated for `isServiceNew`.

More context from @ladonnaq :
We should keep isServiceNew field. If it is true we know we need to engage. Then we would next look at the ReleasedSDK field for product and RelatedSDK field (the one that we can change to be true or false when they onboard and select box indicating existing SDKs enable the product). This way we will catch everything in scope.

So is the service is not new, then we have to look at the product fields.

Not every product will result in a new initial beta SDK but some will so understanding which will helps us to identify TypeSpec candidates. New services who are in scope for our APEX requirements will always be in scope. So we can't rely alone on the lifecycle of the service or the isServiceNew field alone. We can discuss if you like. In the end if the team is working on an initial preview API soec that will result in a initial beta SDK, they are in scope. 😀
