### ISSUE TITLE
APEX Tracking - Redesign to reduce duplication of fields needed before there was a complete release plan 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#7083]
When @praveenkuttappan, @JonathanCrd, and I met last week, we discussed the duplicated information that is in the current epics for tracking APEX.  These fields were all needed to prior to having a completed release plan because: 

- We needed to migrate the existing onboard work item data, which also included SDK release tracking info and there were no package work items available until the SDK release app was deployed (as it creates the packages). 
- We still needed to track SDK release readiness until the SDK release app was deployed.  

```[tasklist]
### Tasks
- [ ] La Donna to figure out how to eliminate duplication of data and update the spreadsheet for Create a release plan, Update a release plan scenarios - https://microsoft-my.sharepoint.com/:x:/p/ladonnaquinn/Ea9NsvoCyaVAjqnfexY7wsQBrlONi9WtSmWNk_l4r-0sfg?e=ZZgT8c
- [x] La Donna to schedule follow-up meeting with @praveenkuttappan and @JonathanCrd to review and get feedback.
- [x] La Donna to build test queries to ensure that it will be easy to track the release plans that are for APEX signoffs.
```

We may need to add a question to the "create a release plan" so that we know for sure if a release plan is being created to satisfy APEX requirement or exception for APEX.  Otherwise - it will be difficult to determine what release plan we need to track for the APEX signoffs.  For example, a product could be in public preview and GA is a year away.  They will likely want to release new Beta SDK versions before GA to address bugs, customer feedback, etc.

**Comment by maririos** [comment]
I believe this has been accomplished and we can close this issue. @ladonnaq  to confirm

**Comment by ladonnaq** [comment]
@maririos - We can close this issue.  I opened this issue which I will use as an epic to track any oustanding work related to data automation.  There were several fields that will require more detailed requirements and potentially UI changes.  I will use this epic to track - https://github.com/Azure/azure-sdk-tools/issues/7495.
