### ISSUE TITLE
When the name of product or service changes, change the title of the work item

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#7115]
Discovered when helping service team with several new services and products that are part of a larger IOT Platform.  They have completed naming and now have new names for several services and products. 

New services and new products often have "code names" until they have completed the official naming review.  The naming review typically has to complete before Public Preview and announcement of the new service and/or new product.  

Today the Azure Devops fields are being updated when there is a new name in service tree or S360/CLC kustos tables.  However, the title is not updated for the triage work item and epic- type product and epic type offering. 

```[tasklist]
### Tasks
- [x] When script that runs to update/synch the service tree/S360 dataverse data to Azure Devops, ensure that if there is a new service name that the epic type service work item is updated with the new name
- [x] When script that runs to update/synch the service tree/S360 dataverse data to Azure Devops, ensure that if there is a new product name that the epic type product and triage work item are updated with the new name.
- [x] Format:  New Name and in parenthesis include the old name.  For example,  Azure IoT Operations Data Processor (previously known as Bluefin).
```

**Comment by maririos** [comment]
@ladonnaq have you seen this to be true? I am not familiar with the logic that syncs existing ADO items with service tree after creation time. 

> Today the Azure Devops fields are being updated when there is a new name in service tree or S360/CLC kustos tables. 

> Format: New Name and in parenthesis include the old name. For example, Azure IoT Operations Data Processor (previously known as Bluefin).

Is this format for the title? will it make the title too long and hard to lead? I will have to look to see if title has a max od characters too

**Comment by maririos** [comment]
FYI I changed the type to request instead of a bug as this was not a requirement we were given before

**Comment by ladonnaq** [comment]
> FYI I changed the type to request instead of a bug as this was not a requirement we were given before

Right now the title is not changing at all.  I thought that the title was being updated in the onboard work items.  Maybe not adding the old name in parenthesis but it was updating the name.  I had to manually update Bluefin.  The triage work item title was not updated.

**Comment by maririos** [comment]
@praveenkuttappan do you know of a flow that is updating the existing ADO items if something in service tree changes?

**Comment by maririos** [comment]
@ladonnaq  could you add here an example of a work item where you saw automation updating the names or fields so we can take a look and see where it is coming from and how?
I talked to Praveen and he is also not aware of such automation :|

**Comment by maririos** [comment]
We looked more into it and found there is a Cloud flow (we didn't know about ) that updates values in the onboarding work items. As we are no longer using these work items, we will change the logic to update ALL work items :)

**Comment by maririos** [comment]
FYI @praveenkuttappan  What we know about the work here is to keep in sync Service Tree, DB, and all work items for fields:

- Service name
- Service current lifecycle stage
- Product name
- Product current lifecycle stage
