### ISSUE TITLE
New initial Beta and new initial Stable SDKs need to be identified in the create a release plan flow 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#7492]
**Requirement:** New initial Beta and new initial Stable SDKs need to be identified in the create a release plan flow by the user as the requirements are different for first initial SDK releases. 

**Scenario:** A service partner has new management plane (ARM) or data plane REST APIs and they plan to release the client and/or management libraries as a new initial SDK package.  The new initial SDK packages should be Beta for 30 days minimum before releasing as stable SDKs.  

```[tasklist]
### Tasks
- [x] Check the value of DataExistingSDKs & MgmtExistingSDKs.  If current value is "no", this indicates that the release plan is for a new initial SDK.  Ask user to confirm the value in the release plan UI.  (Engineering)
- [x] Add new picklist ADO custom field to the release plan work item to identify if release plan is for new initial SDK.  The new custom field name = "isInitialSDK" with string picklist values of "yes" or "no". (La Donna)
- [x] Add new picklist ADO custom field to release plan work item to identify if the release plan is for a Beta or Stable SDK.  The new custom field name = "SDK type to be released" with string picklist values of "beta" or "stable". The current "Create a release plan" UI already ask this question, so all that is needed is for the automation to update this field when a release plan is created.(La Donna)
- [x] Manually migrate relevant data in existing release plans (Data plane SDK release type and Mgmt library release type) to new "isInitialSDK" field. (La Donna)
- [x] Manually migrate relevant data in existing release plans (Data plane SDK release type and Mgmt library release type) to new "SDK type to be released" field.  (La Donna)
- [x] Update automation to update the new fields when a release plan is created. (Engineering)
```

**Comment by ladonnaq** [comment]
FYI @maririos - I completed these tasks today since I was updating the release plan work item. 
- [x] Add new picklist ADO custom field to the release plan work item to identify if release plan is for new initial SDK.  The new custom field name = "isInitialSDK" with string picklist values of "yes" or "no". (La Donna)
- [x] Add new picklist ADO custom field to release plan work item to identify if the release plan is for a Beta or Stable SDK.  The new custom field name = "SDK type to be released" with string picklist values of "beta" or "stable". The current "Create a release plan" UI already ask this question, so all that is needed is for the automation to update this field when a release plan is created.(La Donna)
