### ISSUE TITLE
Reduce duplication of ADO work item fields & automation, validate data in ADO is being updated 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#7495]
Spreadsheet: https://microsoft-my.sharepoint.com/:x:/p/ladonnaquinn/ETD9YCt4cfxHlL4mC1KlVygBIQss1mm6NMIpu3_BdOJhJQ?e=R2eWIs

```[tasklist]
### Tasks
- [ ] https://github.com/Azure/azure-sdk-tools/issues/7509
- [ ] https://github.com/Azure/azure-sdk-tools/issues/7508
- [x] Ensure all service tree metadata and changes in metadata our synced to ADO - https://microsoft-my.sharepoint.com/:x:/p/ladonnaquinn/ETD9YCt4cfxHlL4mC1KlVygBIQss1mm6NMIpu3_BdOJhJQ?e=mgfST9&nav=MTVfe0RENEM1MzJDLUNCMkItNEJFRS1CNTAwLUE3RDMzMTE4MkRGQX0
- [x] Service Tree Link ADO Field value should be updated in the epic type = service. The field is currently in the Triage work item. It can be removed from triage work item. See spreadsheet - https://microsoft-my.sharepoint.com/:x:/p/ladonnaquinn/ETD9YCt4cfxHlL4mC1KlVygBIQss1mm6NMIpu3_BdOJhJQ?e=YjXlRS&nav=MTVfe0RENEM1MzJDLUNCMkItNEJFRS1CNTAwLUE3RDMzMTE4MkRGQX0
- [x] APEX state field can be removed from all work items.  We will no longer need the field.  See spreadsheet - https://microsoft-my.sharepoint.com/:x:/p/ladonnaquinn/ETD9YCt4cfxHlL4mC1KlVygBIQss1mm6NMIpu3_BdOJhJQ?e=YjXlRS&nav=MTVfe0RENEM1MzJDLUNCMkItNEJFRS1CNTAwLUE3RDMzMTE4MkRGQX0
```

**Comment by ladonnaq** [comment]
Closed as complete
