### ISSUE TITLE
Service Tree Metadata Fields and Dashboard/Data Automation Updates 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#7510]
Requirement:  Previously ADO fields containing service tree metatdata was synched when there were changes so that our data in ADO and dataverse is the same as service tree.  During the new data model some of the fields are not being updated.  

```[tasklist]
### Tasks
- [ ] All fields in this excel sheet should be synced when there is changes to the service tree metadata (Gold-Orange rows will have separate GitHub issues because they require new requirements/redesign) - - https://microsoft-my.sharepoint.com/:x:/p/ladonnaquinn/ETD9YCt4cfxHlL4mC1KlVygBIQss1mm6NMIpu3_BdOJhJQ?
- [ ] RP Name and AllRPsService- redesign needed because of changes in service tree metdata - https://github.com/Azure/azure-sdk-tools/issues/7503
- [ ] Move Service Tree Link ADO Field to epic-service and ensure the value is updated if there are changes to the service tree link - https://github.com/Azure/azure-sdk-tools/issues/7508
- [x] Lifecycle metadata needs to be updated anytime there is a change in service tree.  The ADO fields in the epic-product for Lifecycle milestone dates (launch dates) needs always be in synch with service tree - https://github.com/Azure/azure-sdk-tools/issues/7509
```

-

**Comment by ladonnaq** [comment]
@praveenkuttappan - You have completed the last checkbox in this issue. As part of this work did you also do a one-time refresh of all of the products that we have in ADO and release planner.  I ask because I am still seeing no dates or incorrect dates.  The APEX ADO queries that Yoga and I are use are unusable for tracking APEX without accurate dates.  
- [x] Lifecycle metadata needs to be updated anytime there is a change in service tree.  The ADO fields in the epic-product for Lifecycle milestone dates (launch dates) needs always be in synch with service tree - https://github.com/Azure/azure-sdk-tools/issues/7509

Example of missing/no product dates - https://dev.azure.com/azure-sdk/Release/_queries/edit/15320/?queryId=fa0d725a-db96-48fc-9f0f-6a76670d2380.  When I look in service tree this is the lifecycle metadata I see.   Also, I see that the state of the epic-product is Public Preview but the current lifecycle of the product in service tree is GA.  I really need the state and lifecycle launch dates to be an exact match to service tree. These are critical data values for tracking and managing all of the APEX releases.  
![Image](https://github.com/Azure/azure-sdk-tools/assets/67656762/e566d1bc-62de-41be-9f5d-f72b7c55bd1e)

**Comment by ladonnaq** [comment]
Closing and any outstanding todos will be tracked in this issue - https://github.com/Azure/azure-sdk-tools/issues/7495
