### ISSUE TITLE
Show brief survey and prompt user to complete as part of completing a release plan

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#7529]
**Requirement:**  Include a brief survey that will display when a user's completes a release plan. The brief survey should be no more than 3 questions and include a text box for user to provide written feedback.  

**Why:** We are not getting any feedback via the emails requesting feedback.  Presenting the survey in-app when the release plan is completed will likely result in more responses because it is real-time vs emails which are likely lost in the user's inbox. 

```[tasklist]
### Tasks
- [x] Create the survey content @ladonnaq
- [x] Design/requirements for survey - @ladonnaq @JonathanCrd
- [ ] Implementation - TBD
- [ ] Survey results and analysis (include in design/requirements - where is the data stored, how is it accessed, how will we analyze and track outcomes from feedback).
```

**Comment by mario-guerra** [comment]
Hi @ladonnaq, how did you land on three questions? Do you plan to add any questions about release planner or any other aspect of the onboarding process, or are the three reserved for TypeSpec?

**Comment by mario-guerra** [comment]
Here are three questions for TypeSpec:

1. **Learning and Challenges:** Can you share your experience learning TypeSpec and the biggest hurdles you faced during its implementation?
2. **Impact:** How has using TypeSpec affected your project, both positively and negatively? Can you give examples where the tooling made a key difference?
3. **Insights and Suggestions:** What are the main lessons you've learned from using TypeSpec, and how has it changed your project approach? Do you have any suggestions for improving TypeSpec, especially the onboarding process and tooling?

**Comment by ladonnaq** [comment]
Closing and using this issue to track - https://github.com/Azure/azure-sdk-tools/issues/5463
