### ISSUE TITLE
Remove duplicate ADO fields for data from service tree 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#7565]
Requirement:  Remove duplicate fields from ADO work items so that there are not multiple field values to try to maintain in sync with Dataverse. 

```[tasklist]
### Tasks
- [ ] Service Tree Link ADO Field value should be updated in the epic type = service. The field is currently in the Triage work item. It can be removed from triage work item. See spreadsheet - https://microsoft-my.sharepoint.com/:x:/p/ladonnaquinn/ETD9YCt4cfxHlL4mC1KlVygBIQss1mm6NMIpu3_BdOJhJQ?e=YjXlRS&nav=MTVfe0RENEM1MzJDLUNCMkItNEJFRS1CNTAwLUE3RDMzMTE4MkRGQX0
- [ ] APEX state field can be removed from all work items.  We will no longer need the field.  See spreadsheet - https://microsoft-my.sharepoint.com/:x:/p/ladonnaquinn/ETD9YCt4cfxHlL4mC1KlVygBIQss1mm6NMIpu3_BdOJhJQ?e=YjXlRS&nav=MTVfe0RENEM1MzJDLUNCMkItNEJFRS1CNTAwLUE3RDMzMTE4MkRGQX0
- [ ] Product Type, Product Service Tree Link can be removed from Triage work item.  Fields should be in epic type = product. See spreadsheet - https://microsoft-my.sharepoint.com/:x:/p/ladonnaquinn/ETD9YCt4cfxHlL4mC1KlVygBIQss1mm6NMIpu3_BdOJhJQ?e=YjXlRS&nav=MTVfe0RENEM1MzJDLUNCMkItNEJFRS1CNTAwLUE3RDMzMTE4MkRGQX0
```

**Comment by maririos** [comment]
I suggest hidding instead of deleting in case there is some tool depending on that. 
And as we work on this, we should make sure that none of the Release apps or the cloud flows have dependency on the fields

**Comment by ladonnaq** [comment]
Any outstanding gaps are in this issue - https://github.com/Azure/azure-sdk-tools/issues/7495
