### ISSUE TITLE
Ensure all service tree metadata and changes in metadata are synced to ADO work items 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#7566]
Requirement:  Ensure that all of the relevant service tree metadata is in ADO and the field values are updated when there are changes to metadata in service tree.  

Service Partner Feedback:  Service teams keep bringing to our attention that the dates and state of their products in ADO are incorrect.  

Azure SDK Stakeholders/TypeSpec Feedback:  The product launch dates and overall state of the product are not accurate which causes confusing and frustration in using the queries. 

```[tasklist]
### Tasks
- [ ] See spreadsheet - https://microsoft-my.sharepoint.com/:x:/p/ladonnaquinn/ETD9YCt4cfxHlL4mC1KlVygBIQss1mm6NMIpu3_BdOJhJQ?e=fybges&nav=MTVfe0NFNEU1NTIwLUExRjYtNDRFNy1BRTI0LUVFRTRCMzlBNjg3Mn0.
- [x] When the product or service name metdata changes, also update the title of all of the existing ADO work items (triage, epic-product, epic-service, release plans).
```

**Comment by praveenkuttappan** [comment]
Private preview date, public preview date and GA date are now synced from service tree to work items daily if it changes in service tree. RP name and Service RPs fields still require confirmation.

**Comment by ladonnaq** [comment]
> > See spreadsheet
> 
> The ServiceTreeData tab doesn't have color green. If I understand correctly we need to wait until it is green before we should look into it, right?

The orange/gold rows require a change and there are GitHub issue links with requirement info and to track completion.  

- [ ] This issue was for the dates, which we can close now.  Praveen redesigned to handle the date format issue with ADO (which is not something he discovered in implementation) https://github.com/Azure/azure-sdk-tools/issues/7509 
- [ ] This is outstanding yet and we need to queue it up for a work session with engineering to discuss -  https://github.com/Azure/azure-sdk-tools/issues/7503
- [ ] This request was to reduce duplication of data field values - https://github.com/Azure/azure-sdk-tools/issues/7508  I am not sure if this done yet, I will check.

**Comment by ladonnaq** [comment]
Outstanding work will be tracked here - https://github.com/Azure/azure-sdk-tools/issues/7495
