### ISSUE TITLE
SDK Release Readiness APEX milestone:  Remove manual steps and process 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#7575]
**Requirement:**  When service teams complete SDK release readiness in the release planner application notify service partner, Azure SDK APEX team, and mark the corresponding launch criteria as "Completed". 

Previously we used a survey to gather evidence that service partners were on target for releasing their SDKs by the agreed upon timeline.  When service partners use a release plan, we do not need to gather this evidence manaullly anymore. The completion of the Generate SDK step satisfies the SDK release readiness requirement for Public Preview and GA lifecycle milestone APEX requirements.  After this step is complete, then the corresponding ADO field for the launch criteria should be updated as complete. 

Implementation of this feature will increase productivity for the APEX Azure SDK PM Team and the service partner.  Today an estimated of 10 hours is spent by the Azure SDK APEX PM team and the service partner per attestation for Public Preview and GA launch criteria. Since CLC launched in April 2022, we have reviewed and approved 493 Public Preview and GA attestations.  In summary, from April 2022 until today we (us and service partner) have spent 4930 hours/205 days on attestations for Public Preview and GA. 

**Requirements:** 

**UI requirement**
- [ ] Remove the checkbox and link to the survey in the SDK release readiness app.  This can be done first and is not dependent upon the data automation (updating the epic product ADO work item fields to show complete).  All of the docs/process have removed this requirement for signoff. 
-
**Data Automation pre-reqs** 
- [ ] @maririos We will need to identify APEX release plan scenarios as a pre-requisite to automating the ADO field values - https://github.com/Azure/azure-sdk-tools/issues/6262.  We do not need to worry about the last checkbox in the task list of the GitHub issue.  We can remove it b/c it is related to release scenario that is not supported yet. 

**Data Automation**
- [ ] When service teams create a Public Preview or GA release plan and in scope for APEX, Update ADO epic-product launch criteria field as "Incomplete".  See spreadsheet - https://microsoft-my.sharepoint.com/:x:/p/ladonnaquinn/ETD9YCt4cfxHlL4mC1KlVygBIQss1mm6NMIpu3_BdOJhJQ?e=QXgF16&nav=MTVfe0RGQjFGNDY1LTNDM0YtNDJBRi1CNjhFLTZBNUMyQkYyMDZFNX0  

When service teams complete the "Generate SDK" step, SDK release readiness will be considered complete.  At this time the following actions are needed: 
- [ ] Send autogenerated email to service partner contacts for the release plan and copy the azsdkapex@microsoft.com alias 
- [ ] Update ADO epic-product launch criteria field as "Completed".  See spreadsheet - https://microsoft-my.sharepoint.com/:x:/p/ladonnaquinn/ETD9YCt4cfxHlL4mC1KlVygBIQss1mm6NMIpu3_BdOJhJQ?e=QXgF16&nav=MTVfe0RGQjFGNDY1LTNDM0YtNDJBRi1CNjhFLTZBNUMyQkYyMDZFNX0  

**Documentation/Generated Emails** 
- [x] Update the onboard and requirement docs to reflect changes. (La Donna) 
- [ ] Update the email templates sent for API readiness to include SDK release readiness - https://microsoft-my.sharepoint.com/:w:/p/ladonnaquinn/EbrUkOkGf2dLtUzeoEDnszQBh6eqoLR0HIFYDgA8FOdndw?e=8U1eLN (La Donna)

**Comment by ladonnaq** [comment]
@maririos I would like to see this completed and in PROD before end of February.  For reference here is the chart I created for upcoming launches from now until June 01.  The sooner we can get this done the better.  
![image](https://github.com/Azure/azure-sdk-tools/assets/67656762/7a934dc9-5c90-41ec-a82d-d444e62b087f)

**Comment by maririos** [comment]
@ladonnaq follow up questions on the requirements:

> Send autogenerated email to service partner contacts for the release plan and copy the [azsdkapex@microsoft.com](mailto:azsdkapex@microsoft.com) alias

Could you provide the content of the email and who exaclty is the `service partner contacts`?

>Update the onboard and requirement docs to reflect changes.

Is this something you expect us to do? or is this something you can help with once the change is implemented

**Comment by ladonnaq** [comment]
> @ladonnaq follow up questions on the requirements:
> 
> > Send autogenerated email to service partner contacts for the release plan and copy the [azsdkapex@microsoft.com](mailto:azsdkapex@microsoft.com) alias
> 
> Could you provide the content of the email and who exaclty is the `service partner contacts`?
> 
> > Update the onboard and requirement docs to reflect changes.
> 
> Is this something you expect us to do? or is this something you can help with once the change is implemented

Hello @maririos -  Please see the description.  I updated with the todos.  I need to update the docs (which is started drafting last week) and need to create a email template for engineering to send).

**Comment by maririos** [comment]
Changed done in apps:
- Remove `Request Sign Off` tab 
- Remove the check in the data plan

Needs to happen in:
- [ ] Management plane SDK release
- [ ] Data plane SDK release

**Comment by praveenkuttappan** [comment]
I have made the changes in Dataplane SDK release app to remove APEX sign off checkbox and form.
