### ISSUE TITLE
SDK Review Meeting prerequisites check feature

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#7676]
**Requirement:**  Trends in SDK Review Meetings shows that some service partners are scheduling SDK reviews far in advance and then either (a) showing up to the meeting and not completing all of the prerequisites (b) cancelling at the last minute which does not give enough time for another team to take that slot 

Prerequisites: 

1. API Readiness is complete (which means that API Stewardship Board has signed off on the API version). 
2. Generate the data plane libraries. 
3. Generate the API Views for SDK review.
4. Hero/Champion scenario link has been uploaded to the meeting invite. 
5. Write samples for generated library. 

```[tasklist]
### Tasks
- [ ] Confirm all requirements for prerequisite are identified. 
- [ ] Determine which of the prerequisites can be automatically validated. 
- [ ] Determine what the cutoff time is for meeting the prerequisites before the meeting is cancelled.  I would suggest 5 business days/1 week to give time for SDK arch board to review artifacts and also time for another team to grab the timeslot if cancelled. 
- [ ] Identify any UI requirements. 
- [ ] Identify what tools will be impacted (i.e. Release Planner, Scheduling tool, ...). 
```

**Comment by ronniegeraghty** [comment]
Hi @ladonnaq, 
I think we need to call out that the Prerequisites for SDK Reviews are different depending on the type (Intro or Follow Up). 
## Prerequisites: 
### Introduction SDK Review: 
*Note: This review is commended before any public preview but is not a hard requirement.*
1. API Readiness is complete (which means that API Stewardship Board has signed off on the API version).
2. One API View Listing (for an intro meeting this can be taken from the PR to the API Specs repo). 
3. Hero Scenarios (samples that use methods from the API View listing chosen above). 

### Follow Up SDK Review: 
*Note: This review is required before a GA release of the libraries.*
1. Introduction SDK Review is complete (Encompassing all the intro meeting requirements).
2. Generate data plane SDKs
3. Open pull requests to the language repos for the generated libraries. 
4. API Views for all languages release a GA version. Tier 1 languages are required, but if a team in planning to also release Go or other language libraries they also need to be included. We'd like to require that these libraries are generated from a pull request to the specific language repo. Doing so will help minimize duplication API View listings and the need for any additional API View approvals before release. 
5. Hero Scenarios (these can be exactly the same as scenarios used in the intro meeting, they just need to be updated to reflect any changes made in the libraries' surface area since the intro).


Also, with most things we'll need a way to override these checks for the strange one-off scenarios like: 
- Partner team has permission to have their SDK code outside of our language mono repos.

**Comment by ronniegeraghty** [comment]
Checking and Reminder Sending Cadence: 
- Monday mornings and Thursday mornings (I find reminding people at the beginning of the week puts it on the top of their mind when they are planning out their week. And reminding on Thursdays helps gets people to do it on Friday when they have less meetings.) 

When to start sending reminders. 
- The meeting scheduler should start receiving reminders when their scheduled meeting is 3 weeks away or less. 

Email Template for reminders: 
> Hello \<Meeting Scheduler\>, 
Thank you for scheduling an Azure SDK Review for \<Meeting Date\>. 
This is a reminder to add required materials to your meeting at least 2 business days before the scheduled time. This will give our architects enough time to review them and prepare for the meeting. 
Looks like you are still missing the following required materials: 
> - \<List missing materials\> 
> - \<Intro meeting\> An API View listing in at least 1 of the tier 1 programming languages (.NET, Java, JS, or Python). This can be taken directly from your Pull Request to the azure-rest-api-specs repo.
> - \<Intro Meeting\> Code Samples (These should use the APIs from an API View you've submitted)
> - \<Stable Release Meeting\> API View listings in the following languages: <Listing missing languages>. These API View will be automatically generated when you create a pull request into the Azure SDK Language repos. 
> - \<Stable Release Meeting\> Code Samples (These can be written in any of the languages you've submitted any API View for)
> 
> If these materials are not added within 2 business days of the schedule meeting time, this meeting will be automatically canceled. 
>
> If you have any questions about the materials required for you meeting, please reference our [Engineering Hub Docs](https://eng.ms/docs/products/azure-developer-experience/develop/sdk-review?tabs=what-to-bring). 
> 
> Thank you.

**Comment by ronniegeraghty** [comment]
Also, adding a note. We might want to give admins the ability to override materials requirements for specific meetings. 
For when an arch board is scheduled for a more abstract conversation instead of a review.

**Comment by ladonnaq** [comment]
[heart]         LaDonna Quinn reacted to your message:
________________________________

**Comment by ladonnaq** [comment]
[heart]         LaDonna Quinn reacted to your message:
________________________________

**Comment by maririos** [comment]
> Also, adding a note. We might want to give admins the ability to override materials requirements for specific meetings. For when an arch board is scheduled for a more abstract conversation instead of a review.

ohh this is interesting. Could you expand more on this? how will it work?

**Comment by ronniegeraghty** [comment]
> ohh this is interesting. Could you expand more on this? how will it work?

My thought was that, there could be a check box in the admin tool that said something like: 
> [ ] Exempt from materials requirements
And if checked the meeting does get check for it's materials, set reminders, or auto canceled.

**Comment by ladonnaq** [comment]
[heart]         LaDonna Quinn reacted to your message:
________________________________

**Comment by maririos** [comment]
> And if checked the meeting does get check for it's materials, set reminders, or auto canceled.
One example is the meetings that arch board has been having around Aspire. There aren't always libraries prepared since the architects are giving pre-implementation advice to the Aspire team.

So the flow will be:
- User goes to the Scheduler tool and creates an Introduction SDK meeting
- Admin sees the meeting in the Admin tool (or someone pings them) and they can check a box in the admin tool that will stop the reminders and the automatic cancellation 

Is this correct?

**Comment by ronniegeraghty** [comment]
> Is this correct?

Yes. We can add a thing to the reminder email that says:
> if you feel these materials don't apply to your review meeting, please contact the Azure SDK Architecture Board Help Desk(azsdkarch-help@microsoft.com).

**Comment by maririos** [comment]
> TODO:   On scheduling side surface the languages that were selected in the release planner. 

I think there was an attempt to do this, but work needs to be checked.

**Comment by maririos** [comment]
Templates we have. Looks like they need a little change:
- SDK Review - Missing Requirements Reminder Email

Hello [User Name],

You upcoming SDK review meeting ([Event Name]) on ([Event Date]) is missing API links for the following languages: ([languages missing]).
Please update this data through this link on the Scheduler app before 48 hours of this meeting or it will be automatically cancelled.

Thanks,
The Azure SDK team.

- SDK Review - Missing Requirements - Auto cancelation message

Hello [User Name],

You upcoming SDK review meeting ([Event Name]) on ([Event Date]) was automatically canceled due to missing requirements related to these language SDKS: ([languages missing]).

Please use Scheduler app to schedule a new meeting when you're ready.

Thanks,
The Azure SDK team
