### ISSUE TITLE
[APIView] APIRevison MetaData

### ISSUE THREAD

**Issue by chidozieononiwu** [Azure/azure-sdk-tools#7744]
Adding more metadata to APIRevisions to make it easier for architects to work with

### Tasks

- [ ] https://github.com/Azure/azure-sdk-tools/issues/7752
- [ ] https://github.com/Azure/azure-sdk-tools/issues/7753
- [ ] https://github.com/Azure/azure-sdk-tools/issues/1696
- [ ] https://github.com/Azure/azure-sdk-tools/issues/2278
- [ ] https://github.com/Azure/azure-sdk-tools/issues/8678
- [ ] For Pull Request APIRevisons add PR Source branch name to APIRevision
- [ ] Don't add labels for Automatic and Pull Request APIRevisions instead generate it from the metadata

**Comment by tjprescott** [comment]
Closing this since the only remaining work item is #7752 which is a separate issue.
