### ISSUE TITLE
TypeSpec data related to interval between start and completion of tasks, milestones, and overall release plan

### ISSUE THREAD

**Issue by MrJustinB** [Azure/azure-sdk-tools#7769]
Related GitHub issues: 

- [x] https://github.com/Azure/azure-sdk-tools/issues/7878
- [x] https://github.com/Azure/azure-sdk-tools/issues/7890

Most of metrics requested in related GitHub issues is not accessible via current engagement data model.  We can revisit when we begin planning for Selenium to determine feasibility of obtaining the data. 

Meeting notes:
•	TypeSpec data dashboard: Justin and Mariana will work on creating a dashboard that shows the average and outlier times for service teams to go through the TypeSpec pipeline, as requested by Mario, the TypeSpec PM. We discussed a visual timeline with major milestones along the timeline and average time to get to each milestone and then show the outliers for each (i.e. which service teams were slower and which were faster) so that Mario can follow up to understand challenges faced.
•	Data plane vs management plane: Mario wants to see the distinction between data plane and management plane services in the dashboard, to understand if there is a significant difference in their TypeSpec experience.
•	TypeSpec adoption: Mario is less interested in tracking the adoption of TypeSpec, since it is now mandated for all service teams, but he would like to see how many services have moved to TypeSpec as a secondary metric.
Follow-up tasks:

- [x] Create a dashboard for TypeSpec metrics: Figure out how to collect the data for the average and outlier times for service teams to go through the TypeSpec pipeline.  
Jonathon has provided PowerBI Report with data to Mario.  Link - https://msit.powerbi.com/groups/3e17dcb0-4257-4a30-b843-77f47f1d4121/reports/a98bc8dc-dceb-4c04-a288-932e5ab5fed5?ctid=72f988bf-86f1-41af-91ab-2d7cd011db47&bookmarkGuid=4bac8027-4970-46f6-a150-e818878d8dd7&experience=power-bi

- [ ] Extend the PowerBI Report provided by Jonathon to include visuals.  (Angelos and La Donna)  
Angelos is working on options for visuals.  @mario-guerra - Angelos has one example created so far.  Let us know if you find this visual useful. 
![image](https://github.com/Azure/azure-sdk-tools/assets/67656762/5a0a5251-3306-4e03-a6df-90b56ec34d50)

**Comment by MrJustinB** [comment]
Mario:  "Thanks Justin, one other thing that just occurred to me – it would be good to differentiate between greenfield and brownfield services in the averages."

**Comment by maririos** [comment]
- Questions to answer:
  - How long does it take to finish a release plan
  - How long does each milestone and each task in the milestone 
- Be able to distinguish:
  - Management plane vs Data plane
  - TypeSpec or not TypeSpec   

Ideas on what we should do:
- PowerBi dashboard from DataVerse diectly as the DB has the date the specific task or milestone was completed
- It shouldn't take more than 1 to 1.5 days building
- This is a temporary view as there are way too many variables to take this data as accurate

**Comment by ladonnaq** [comment]
@MrJustinB @maririos I believe that you are using this issue to track the work that you are doing for Mario for TypeSpec dashboard.  I have added a table to track the metrics and information needed.  I wanted to sync on the approach and todos so we capture for now and next semester.  

- I think it would be best to create a dashboard view within the current release planner PowerBI report.  We could start by showing the data we do have like release plans data for TypeSpec (data vs mgmt plane), upcoming releases for TypeSpec (based on release plan target date), etc.  PowerBI is more user friendly and better for getting a program level view for reporting and understanding insights vs ADO.  ADO is the tool we use for APEX because we are actively updating and maintaining the ADO artifacts throughout the engagement.  (i.e. copying and pasting information that was in email but important like extension details, ....).  It is also the tool most frequently used by service partners for tracking their upcoming new product/service releases and also the tool we use to track SDK releases. 
- I consider this part of the work to continue to ensure that the engagement experience model is aligned across the systems of record so added it to this epic - https://github.com/Azure/azure-sdk-tools/issues/7822.  

![image](https://github.com/Azure/azure-sdk-tools/assets/67656762/6c1c1ff0-b1c6-4993-8039-fc4e75159829).

**Comment by MrJustinB** [comment]
> > I wanted to sync on the approach and todos so we capture for now and next semester.
> 
> This work is done from eng side and we have sent it to Mario who can now modify it and own it. I don't expect Eng Team to do any other work in this dashboard

That was not the expectation. My expectation is that we would own the dashboard and enhance over time. Mario's recent enhancement request is to be able to show a visual trend i.e. how are the time going up/down over time.

**Comment by maririos** [comment]
Eng exp team can def own it. I am saying Eng team gave all the data needed and now for visualization, we can have PM team work on that.
We can talk more about this tomorrow in our sync.

**Comment by mario-guerra** [comment]
@maririos, @AngelosP, @MrJustinB, @ladonnaq would it be helpful to have a sync meeting to discuss the current state and clarify expectations one what the TypeSpec team wants to see?
CC @allenjzhang for awareness.

**Comment by ladonnaq** [comment]
Hello @mario-guerra, I sent you an email but also adding a comment to this GitHub issue.  Can you look at the data in the report and the example visual that Angelos created?  We can continue to improve this dashboard but I want to make sure that you (and the TypeSpec) find the data valuable. Also, we should only be looking at the 2024 data.  The MVP Release Planner and data model was not complete for non-APEX scenarios until beginning of Feb 2024.

**Comment by maririos** [comment]
@MrJustinB I believe this is no longer needed. Please confirm and close as appropiate

**Comment by MrJustinB** [comment]
Agreed
