### ISSUE TITLE
Support for extensions for APEX 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#7913]
Requirement:  When a release plan is created, allow the user to identify if the release plan is for an APEX extension.  Update relevant ADO fields in the release plan work item. 

**Release Plan creation** 
- [ ] "Create a release plan" UI needs to be updated to allow a user to identify the release plan is for completing APEX extension work.  (Engineering) 
- [x] New field on release plan summary in release details to identify extension.  IsExtension with values of "yes" or "no". (La Donna)
- [ ] Requirements for data automation for updates to APEX lifecycle state fields in the product epic. (La Donna) 
- [ ] Existing automation needs to be updated so that the isExtension field value is updated based on user input and APEX lifecycle state fields need to be updated.  (Engineering) 

**Release plan completed** 
- [ ] Existing automation needs to be updated so that the relevant APEX lifecycle state fields and the relevant APEX launch criteria fields values are changed to "Complete". 
- [ ] Requirements for data automation for updates to APEX lifecycle state fields and APEX launch criteria fields in the product epic. (La Donna)

**Comment by ladonnaq** [comment]
FYI @maririos - I completed this task today since I was updating the release plan work item.  I also reduced the complexity of the requirement so it should take less time to complete.   
- [x] New field on release plan summary in release details to identify extension.  IsExtension with values of "yes" or "no". (La Donna)

**Comment by ladonnaq** [comment]
Closed as not in plan.  We are leveraging S360 exception process, and the release plans will be identified as extension as part of this epic - https://github.com/Azure/azure-sdk-tools/issues/6262
