### ISSUE TITLE
Update .NET parser with new tokens tree structure

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#7922]
```[tasklist]
### Tasks
- [x] Update DotNet Parser to Tree Token Structure
- [x] Write Documentation for Tree Token APIView CodeFile
- [x] Update UI to display tree style tokens in APIView  (Take the opportunity to implement lazy loading)
```
