### ISSUE TITLE
SDK Automation Tooling's Enhancements

### ISSUE THREAD

**Issue by raych1** [Azure/azure-sdk-tools#8039]
**Overview**
This issue is created to track all the work items related to the [Enhancements-to-SDK-Automation](https://microsoftapc-my.sharepoint.com/:w:/g/personal/raychen_microsoft_com/ERNfQJZNSjFFo7hOvhsQQSYBDeogQLWKXHkrzeyjkNJDeQ?e=sHKcHq) specification.

**1. Support Scenarios**
- `TypeSpec` green field services.
   This is currently supported by all four languages (.NET, Java, Python, JS). 
   Add the support for Go language.
- `TypeSpec` brown field services.
   Generation strategy to handle the existing customized SDK code: 
    - option 1: keep the existing customized SDK code and generate the SDK code based on `TypeSpec` specs. 
    If the customized SDK code is not compatible with the new specs, the generation should fail in the build/compile step providing the comprehensive error message, such as "The SDK has customized SDK code and might not be compatible with the new specs, the service team may need to update the customized code or the new specs."
    - option 2: remove the existing customized code then generate the SDK code from scratch based on the `TypeSpec` specs
- Service group with a mix of service using `TypeSpec` and service using the `Swagger`.
   The prerequisite is each service must have individual SDK package.

```[tasklist]
### Tasks
- [ ] https://github.com/Azure/azure-sdk-for-net/issues/41746
- [ ] https://github.com/Azure/azure-sdk-for-net/issues/42159
- [ ] https://github.com/Azure/azure-sdk-tools/issues/8055
- [ ] https://github.com/Azure/azure-sdk-tools/issues/8056
- [ ] https://github.com/Azure/azure-sdk-tools/issues/8057
- [ ] https://github.com/Azure/azure-sdk-tools/issues/8308
- [ ] https://github.com/Azure/azure-sdk-tools/issues/8309
- [ ] https://github.com/Azure/azure-sdk-tools/issues/8712
```

**2. Define the Required Steps**
There are a bunch of steps to be executed during the SDK generation process. Take .NET for example, it includes the following steps: 
- Environment setup
- SDK generation
- SDK code building, which include test/sample code building
- SDK code packing
- API export
- Breaking change validation
- API View generating

Any failure of the above steps would cause the SDK generation CI check fail. We will need to identify the required steps to run in the spec pull request phase for each SDK language. It's important to note that the required steps may vary across languages, as the requirement could differ from one language to another.

```[tasklist]
### Tasks
- [ ] https://github.com/Azure/azure-sdk-tools/issues/8040
- [ ] https://github.com/Azure/azure-sdk-tools/issues/8041
- [ ] https://github.com/Azure/azure-sdk-tools/issues/8042
- [ ] https://github.com/Azure/azure-sdk-tools/issues/8043
- [ ] https://github.com/Azure/azure-sdk-tools/issues/8044
- [ ] https://github.com/Azure/azure-sdk-tools/issues/8059
- [ ] https://github.com/Azure/azure-sdk-tools/issues/8417
- [ ] https://github.com/Azure/azure-sdk-tools/issues/8416
- [ ] https://github.com/Azure/azure-sdk-tools/issues/8415
```
**3. Breaking Change Detection**
The automation should be able to detect the breaking changes against SDK API level.

```[tasklist]
### Tasks
- [ ] https://github.com/Azure/azure-sdk-tools/issues/8045
- [ ] https://github.com/Azure/azure-sdk-tools/issues/8046
- [ ] https://github.com/Azure/azure-sdk-tools/issues/8477
```
**4. `tsp-client` adoption**
Adopt `tsp-client` to replace the common powershell script to interact with `tsp-config.yaml`, fetch the `TypeSpec` specs, and run `TypeSpec` language emitters. 
This could improve the logging experience for the steps `tsp-client` tool covers.

```[tasklist]
### Tasks
- [ ] https://github.com/Azure/azure-sdk-tools/issues/8047
- [ ] https://github.com/Azure/azure-sdk-tools/issues/8048
- [ ] https://github.com/Azure/azure-sdk-tools/issues/8049
- [ ] https://github.com/Azure/azure-sdk-tools/issues/8050
```
**5. Logging Improvement**
Refine the error logs to enhance clarity and conciseness, provide guidance on corrective actions, and include relevant document links as necessary. The logging should include three parts information if possible.
- error code or error message
- next steps or suggested actions
- associated document links if have

```[tasklist]
### Tasks
- [ ] https://github.com/Azure/azure-sdk-tools/issues/8058
- [ ] https://github.com/Azure/azure-sdk-tools/issues/7958
- [ ] https://github.com/Azure/azure-sdk-tools/issues/8095
- [ ] https://github.com/Azure/azure-sdk-tools/issues/8096
- [ ] https://github.com/Azure/azure-sdk-tools/issues/8097
- [ ] https://github.com/Azure/azure-sdk-tools/issues/8098
- [ ] https://github.com/Azure/azure-sdk-tools/issues/8099
- [ ] https://github.com/Azure/azure-sdk-tools/issues/8100
- [ ] https://github.com/Azure/azure-sdk-tools/issues/8122
- [ ] https://github.com/Azure/azure-sdk-tools/issues/8250
- [ ] https://github.com/Azure/azure-sdk-tools/issues/8495
- [ ] https://github.com/Azure/azure-sdk-tools/issues/8688
- [ ] https://github.com/Azure/azure-sdk-tools/issues/8658
- [ ] https://github.com/Azure/azure-sdk-tools/issues/8649
- [ ] https://github.com/Azure/azure-sdk-tools/issues/8563
- [ ] https://github.com/Azure/azure-sdk-tools/issues/8722
```
**6. Bugs identified**

```[tasklist]
### Tasks
- [ ] https://github.com/Azure/azure-sdk-tools/issues/7631
- [ ] https://github.com/Azure/azure-sdk-tools/issues/7760
- [ ] https://github.com/Azure/azure-sdk-tools/issues/8013
- [ ] https://github.com/Azure/azure-sdk-tools/issues/7458
- [ ] https://github.com/Azure/azure-sdk-tools/issues/7950
- [ ] https://github.com/Azure/azure-sdk-tools/issues/7957
- [ ] https://github.com/Azure/azure-sdk-tools/issues/7968
- [ ] https://github.com/Azure/azure-sdk-tools/issues/7967
- [ ] https://github.com/Azure/azure-sdk-tools/issues/8087
- [ ] https://github.com/Azure/azure-sdk-tools/issues/7966
- [ ] https://github.com/Azure/azure-sdk-tools/issues/8101
- [ ] https://github.com/Azure/azure-sdk-tools/issues/8218
- [ ] https://github.com/Azure/azure-sdk-tools/issues/7235
- [ ] https://github.com/Azure/azure-sdk-tools/issues/8360
- [ ] https://github.com/Azure/azure-sdk-tools/issues/8380
- [ ] https://github.com/Azure/azure-sdk-tools/issues/8381
- [ ] https://github.com/Azure/azure-sdk-tools/issues/8603
- [ ] https://github.com/Azure/autorest.csharp/issues/4946
```

**7. Documentation**
Provide documentation of error definitions and suggestions for the fixes for each language and the common SDK automation framework.

**8. Additional Tasks**
```[tasklist]
### Tasks
- [ ] https://github.com/Azure/azure-sdk-tools/issues/8111
- [ ] https://github.com/Azure/azure-sdk-tools/issues/8353
- [ ] https://github.com/Azure/azure-sdk-tools/issues/8701
- [ ] https://github.com/Azure/azure-sdk-tools/issues/8710
- [ ] https://github.com/Azure/azure-sdk-tools/issues/8418
```

**Comment by raych1** [comment]
All of the linked tasks have been completed except for the one to add how-to-fix suggestions for .NET. I will close this EPIC and track that in API to SDK automation board separately.
