### ISSUE TITLE
APIView Yet Another reArchitecting of APP

### ISSUE THREAD

**Issue by chidozieononiwu** [Azure/azure-sdk-tools#8174]
Attempting to implement various requested features in APIView have many times proved difficult or impossible. Most of these are due to the current architecture of APIView and others are limitations in ASP.NET MVC framework. For a while I have been exploring way to rearchitect APIView such that many of these features can be implemented in a robust non-hacky manner. This issue explains the coming changes and a timeline for completing them.

The main idea is to decouple the presentation code from most of the logic by exposing a robust APIView API (this is one of our user requests), then replacing the client side with a progressive web application that offers many tools for modern and rapid web development out of the box. The goal here is that the API would be as useful as the client application such that one could potentially build a different client (say VS code) to run off it or just use the API directly. The PWA front end will run side by side with existing ASP.NET until we decide to retire the later.  

A lot of this work is already done. Below is a time frame for completion.

- [x] Index Page , Review & APIRevison API endpoint - Completed Not deployed.
    **Issues Resolved**
    -  https://github.com/Azure/azure-sdk-tools/issues/2282
    - https://github.com/Azure/azure-sdk-tools/issues/3159
    - https://github.com/Azure/azure-sdk-tools/issues/4747

- [x] Review Page, API endpoint for APITree Tokens, and Comments, Approval e.t.c.
    **Issues Resolved**
    - The main issue that will be addressed here is the addition of true lazy loading so we don't experience page  performance issue when loading documentation or packages with large number of APIs.
    - We also enable many features request that we cannot currently implement properly due to limitations of UI components of native ASP.Net MVC.

**Requests from Feedback Session May 23rd 2024**
- [x] Pinned APIRevision  (Latest GA, Latest Approved, Current Main, Latest Released). Shown as regular dropdown items with appropriate tags, pinned to the top of the dropdown list.
- [x] Re-Order filters in API Revision Select: Approved, Released, Auto, Manual, PR.
- [x] Use Auto, Manual, PR Icons on filter buttons and add tooltip over icons.
- [x] Move Filter buttons bellow search text box.
- [x] Add option for disabling lazy loading of code-panel rows (so all row are present on page at once) https://github.com/Azure/azure-sdk-tools/issues/8716
- [ ] Add ability to search code-panel rows in lazy loaded state. https://github.com/Azure/azure-sdk-tools/issues/8716
- [x] Add Diff styles. Full Diff (Full API with diff shown), Tree Diff (Only nodes with diff in descendant but show full content), Node Diff (Only nodes with diff in descendant but show only the nodes with diff and some context around them).

**What's required to Deploy to Production**
This will be made available on language basis with C# and Java being the first
- [x] Script run against original files to generate tree style tokens stored alongside flat list of tokens.
- [x] Update Automatic and Pull Request API to support tree tokens. (Basically, Comparing API Revisions to evaluate if there is a change)
- [x] Feature Parity with regular APIView. Approval, Request Reviewers, Subscribe, Mark as Viewed, Change History Display, Navigation Jumps
- [ ] Sample Page - Completed at later date

```[tasklist]
### Required to close the epic
- [ ] https://github.com/Azure/azure-sdk-tools/issues/8694
- [ ] https://github.com/Azure/azure-sdk-tools/issues/8695
- [ ] https://github.com/Azure/azure-sdk-tools/issues/8715
- [ ] https://github.com/Azure/azure-sdk-tools/issues/8743
- [ ] https://github.com/Azure/azure-sdk-tools/issues/7735
- [ ] https://github.com/Azure/azure-sdk-tools/issues/8839
- [ ] https://github.com/Azure/azure-sdk-tools/issues/8705
- [ ] https://github.com/Azure/azure-sdk-tools/issues/8704
- [ ] https://github.com/Azure/azure-sdk-tools/issues/8742
- [ ] https://github.com/Azure/azure-sdk-tools/issues/8762
```

```[tasklist]
### Other issues to keep in mind while working on this
- [ ] https://github.com/Azure/azure-sdk-tools/issues/4737
- [ ] #5585
- [ ] #6114
- [ ] https://github.com/Azure/azure-sdk-tools/issues/6132
- [ ] https://github.com/Azure/azure-sdk-tools/issues/5571
- [ ] https://github.com/Azure/azure-sdk-tools/issues/8716
```

@maririos @praveenkuttappan @JonathanGiles
