### ISSUE TITLE
APIRevision Management

### ISSUE THREAD

**Issue by chidozieononiwu** [Azure/azure-sdk-tools#8240]
This epic that tries to address various issue we have around managing APIRevisions (Creating, Updating, Tagging with Versions, release tags e.t.c.)

The main goal here is to clarify and document this process so we fully understand the workflow for managing API Revisions then translate it into code in such a way that each step in the process is properly logged such that one can easily track down problem in our DevOps pipelines.

Mappend workflows: https://www.figma.com/board/6qYeMjBRr3egz4MycRNglA/APIView-Workflow-Versions?node-id=0-1

### Tasks

- [x] Create a workflow document that covers existing behavior for all cases.
- [ ] Collect feedback from architects and other users, then update the document to cover new requests.
- [ ] Design APIs around the workflow.
- [ ] Implement the APIs

**Comment by tjprescott** [comment]
Assigning to myself to review the Figma and understand how to carry this forward.
