### ISSUE TITLE
New data Create a release plan feature: Manually update the new ADO data field values for existing ADO artifacts

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#8541]
### Tasks
- [x] Update isAPEX field value in Release Plan work item
- [ ] Update isExtension field value in Release Plan work items that State does not equal "Finished"
- [ ] Update isInitialSDK field value in Release Plan work items that State does not equal "Finished"
- [ ] Ensure that all APEX lifecycle and requirement ADO field values in existing ADO epic-product type work items are accurate (match S360/CLC)
