### ISSUE TITLE
[SDK Automation - JS] Maintenance

### ISSUE THREAD

**Issue by wanlwanl** [Azure/azure-sdk-tools#8579]
```[tasklist]
### Tasks
- [ ] https://github.com/Azure/azure-sdk-tools/issues/8487
- [ ] https://github.com/Azure/azure-sdk-tools/issues/8522
- [ ] https://github.com/Azure/azure-sdk-tools/issues/8592
- [x] Ts emitter plan to change file name: https://github.com/Azure/autorest.typescript/pull/2728#discussion_r1704817554
- [x] https://github.com/Azure/azure-sdk-tools/security/dependabot/137
```
