### ISSUE TITLE
Increase support for APIView in C/C++ repositories

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#8741]
```[tasklist]
### Tasks
- [ ] https://github.com/Azure/azure-sdk-tools/issues/8821
- [ ] https://github.com/Azure/azure-sdk-tools/issues/8822
- [ ] https://github.com/Azure/azure-sdk-tools/issues/8823
```
