### ISSUE TITLE
Move Samples page to new APIView UI

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#8742]
There are currently existing issues with this page. For now the main focus is to see how we can enable it (even if minimim support) for languages that are using the new UI
```[tasklist]
### Tasks
- [ ] https://github.com/Azure/azure-sdk-tools/issues/4881
- [ ] https://github.com/Azure/azure-sdk-tools/issues/4547
- [ ] https://github.com/Azure/azure-sdk-tools/issues/7642
```

**Comment by maririos** [comment]
Add:
- Features
- Time commitment
- Deployment plan
