### ISSUE TITLE
Service only Onboarding scenarios (bugs/issues introduced by redesign) 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#8938]
Requirement: Resolve issues introduced with redesign of onboarding feature that have impacted the "service only" scenarios. 

 Link to Onboarding Scenarios - https://microsoft-my.sharepoint.com/:x:/p/ladonnaquinn/EQOYpXEI_V5Em4S2atNe0JABJn3HmJyJP8_f5kSepo6EgQ?e=6pXt7f&nav=MTVfezhBMjYxQUZFLTA4NzEtNEJENy05NDU1LUIzQTdENTM1QjQ4Mn0

**Scenarios 27-32 are Service onboarding scenarios.**  
<img width="248" alt="image" src="https://github.com/user-attachments/assets/3e9e0451-c88b-4a0b-a9f6-fcfa600bc9cf">

**UI Updates**
<img width="325" alt="image" src="https://github.com/user-attachments/assets/b097afce-eced-4d82-a8b8-d971ee8773a6">

**API details message** 
The more info icon has link to APEX docs.  APEX docs - [Program Overview | Service Lifecycle & Actions Team (eng.ms)](https://eng.ms/docs/cloud-ai-platform/azure-core/azure-core-pm-and-design/trusted-platform-pm-karimb/service-lifecycle-and-actions-team/service-lifecycle-actions-team/apex/media/overview)

<img width="368" alt="image" src="https://github.com/user-attachments/assets/c381a7dd-eaef-493a-8ece-cc72bd53b399">

### Tasks
- [ ] No autogenerated email for any of the service only scenarios
- [ ] Triage work item fields have the expected data values.
- [ ] Epic-Service does not have the values for the following fields: DataScope, MgmtScope, DataExistingSDKs, MgmtExistingSDKs
- [ ] UI updates to notify user that APEX scope is at the Product level not Service.
- [ ] Validate this requirement is met (I think so but want to confirm) -  In the "Service only" onboard a scenario, a epic-Service work item is created.  When a product is onboarded ensure that the product is mapped to the epic-Service that was onboarded previously.

**Comment by ladonnaq** [comment]
@ckairen @maririos  This is ready for your review.  Thanks!  :-)
