### ISSUE TITLE
Clarify which REST API scope is unsure 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#8944]
Requirement:  State specifically which REST API Scope was unsure in the email. 

<img width="522" alt="image" src="https://github.com/user-attachments/assets/0d6a611b-18f3-472c-8b06-822e77123eef">

```[tasklist]
### Tasks
- [ ] IF DataScope = unsure THEN "Data plane scope was indicated as unsure." 
- [ ] IF MgmtScope = unsure THEN "Management plane scope was indicated as unsure." 
- [ ] IF DataScope = unsure AND MgmtScope = unsure THEN "Data and management plane scope were indicated as unsure." This scenario would not include the "API targets management plane (ARM) uses RPaaS" text.  
```
