### ISSUE TITLE
Optimize support efficiency by integrating relevant contact information at the corresponding stage within the workflow. 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#8987]
Requirement: Provide relevant contact information within the workflow at the relevant task/step.  

For example, see screenshot below. 

<img width="484" alt="image" src="https://github.com/user-attachments/assets/8ee2ebdf-f787-4004-945e-07c096124e9f">

```[tasklist]
### Tasks
- [ ] Determine which steps require the support contact information.  
- [ ] Draft UI changes and review with Design team. 
- [ ] Provide list of requirements to engineering (URLs, UI updates, etc).  
- [ ] Engineering implements. 
```
