### ISSUE TITLE
Service Partner Dashboard V2:  SDK Customer Support enhancements  

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#8989]
**Requirement:**  Redesign of Service partner dashboard to include Customer reported issues and release plan alerts & notifications. 

**Depends on the work on:** https://github.com/Azure/azure-sdk-tools/issues/7366

```[tasklist]
### Tasks
- [ ] Define process and SLAs that we expect service teams to meet for managing customer reported GitHub issues (Engagement PM + SDK Language & Support PMs)
- [ ] Communication and adoption plan  
- [ ] Redesign UI of Service Partner Dashboard to include Customer reported issues, as well as new feature for notifications & alerts 
- [ ] Determine requirements to block SDK releases if SLAs are not met 
- [ ] Review with engineering before hand-off 
- [ ] Engineering implementation and scenario testing 
```
