### ISSUE TITLE
Update text on SDK details screen for Onboarding feature

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#9172]
**Issue:**  Feedback from service and business partners indicates that the question is confusing. When onboarding a new product, they are usually updating the new API version, and there isn't a new SDK version that enables the product yet. They interpret the statement to mean that there are already published SDKs enabling the product, so they are not selecting it. This misunderstanding is causing Brownfield Scenarios to be incorrectly identified as Greenfield Scenarios. We need to update the statement to clearly ask if there are existing Service SDKs that will include contributions from the product.

**Current UI:** 
![Image](https://github.com/user-attachments/assets/850f8721-1a75-436b-94c9-27a4b3b2e852)

**Updated UI:** 
![Image](https://github.com/user-attachments/assets/1a653b22-824d-4910-a41d-956cd75456be)

**TODOs:** 
- [ ] Update statements in the UI 
- [ ] "Existing public management plane SDKs will incorporate contributions from the product."
- [ ] "Existing public data plane SDKs will incorporate contributions from the product." 
- [ ] In the information icon include "Check the Azure SDK release page if you're unsure about existing SDKs for the Service - https://aka.ms/azsdk/releases"

**Comment by maririos** [comment]
@ladonnaq 

> "Existing public management plane SDKs will incorporate contributions from the product."

Could be my English, but this statement still creates confusion. Other alternatives:

1. "Will this product contribute to an existing public management plane SDKs?"
2. "Does this product requires updates to existing public management plane SDKs?"

My vote is for 1.

**Comment by ladonnaq** [comment]
> [@ladonnaq](https://github.com/ladonnaq)
> 
> > "Existing public management plane SDKs will incorporate contributions from the product."
> 
> Could be my English, but this statement still creates confusion. Other alternatives:
> 
> 1. "Will this product contribute to an existing public management plane SDKs?"
> 2. "Does this product requires updates to existing public management plane SDKs?"
> 
> My vote is for 1.

I originally wrote a question similar to #1 above but then changed it to a statement so it would work with the current UI.  However, I think the question format will be easier for users to understand.  I vote for #1.
